// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   * @return Whether the formattedAddress field is set.
   */
  boolean hasFormattedAddress();
  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   * @return The formattedAddress.
   */
  google.maps.fleetengine.v1.FormattedAddress getFormattedAddress();
  /**
   * <pre>
   * A full, human-readable address for this place.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.FormattedAddress formatted_address = 1;</code>
   */
  google.maps.fleetengine.v1.FormattedAddressOrBuilder getFormattedAddressOrBuilder();
}
