// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicles.proto

package google.maps.fleetengine.v1;

public interface BatteryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.BatteryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Status of the battery, whether full or charging etc.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
   * @return The enum numeric value on the wire for batteryStatus.
   */
  int getBatteryStatusValue();
  /**
   * <pre>
   * Status of the battery, whether full or charging etc.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.BatteryStatus battery_status = 1;</code>
   * @return The batteryStatus.
   */
  google.maps.fleetengine.v1.BatteryStatus getBatteryStatus();

  /**
   * <pre>
   * Status of battery power source.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
   * @return The enum numeric value on the wire for powerSource.
   */
  int getPowerSourceValue();
  /**
   * <pre>
   * Status of battery power source.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.PowerSource power_source = 2;</code>
   * @return The powerSource.
   */
  google.maps.fleetengine.v1.PowerSource getPowerSource();

  /**
   * <pre>
   * Current battery percentage [0-100].
   * </pre>
   *
   * <code>float battery_percentage = 3;</code>
   * @return The batteryPercentage.
   */
  float getBatteryPercentage();
}
