// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

public interface FormattedAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.FormattedAddress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The lines of text that describe the address.
   * At least one line must be present.
   * </pre>
   *
   * <code>repeated string lines = 1;</code>
   * @return A list containing the lines.
   */
  java.util.List<java.lang.String>
      getLinesList();
  /**
   * <pre>
   * The lines of text that describe the address.
   * At least one line must be present.
   * </pre>
   *
   * <code>repeated string lines = 1;</code>
   * @return The count of lines.
   */
  int getLinesCount();
  /**
   * <pre>
   * The lines of text that describe the address.
   * At least one line must be present.
   * </pre>
   *
   * <code>repeated string lines = 1;</code>
   * @param index The index of the element to return.
   * @return The lines at the given index.
   */
  java.lang.String getLines(int index);
  /**
   * <pre>
   * The lines of text that describe the address.
   * At least one line must be present.
   * </pre>
   *
   * <code>repeated string lines = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the lines at the given index.
   */
  com.google.protobuf.ByteString
      getLinesBytes(int index);
}
