// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/trip_api.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * GetTrip request message.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.GetTripRequest}
 */
public final class GetTripRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.GetTripRequest)
    GetTripRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTripRequest.newBuilder() to construct.
  private GetTripRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTripRequest() {
    name_ = "";
    view_ = 0;
    routeFormatType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTripRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTripRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            google.maps.fleetengine.v1.RequestHeader.Builder subBuilder = null;
            if (header_ != null) {
              subBuilder = header_.toBuilder();
            }
            header_ = input.readMessage(google.maps.fleetengine.v1.RequestHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(header_);
              header_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (currentRouteSegmentVersion_ != null) {
              subBuilder = currentRouteSegmentVersion_.toBuilder();
            }
            currentRouteSegmentVersion_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentRouteSegmentVersion_);
              currentRouteSegmentVersion_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (remainingWaypointsVersion_ != null) {
              subBuilder = remainingWaypointsVersion_.toBuilder();
            }
            remainingWaypointsVersion_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(remainingWaypointsVersion_);
              remainingWaypointsVersion_ = subBuilder.buildPartial();
            }

            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            routeFormatType_ = rawValue;
            break;
          }
          case 74: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (currentRouteSegmentTrafficVersion_ != null) {
              subBuilder = currentRouteSegmentTrafficVersion_.toBuilder();
            }
            currentRouteSegmentTrafficVersion_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentRouteSegmentTrafficVersion_);
              currentRouteSegmentTrafficVersion_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (remainingWaypointsRouteVersion_ != null) {
              subBuilder = remainingWaypointsRouteVersion_.toBuilder();
            }
            remainingWaypointsRouteVersion_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(remainingWaypointsRouteVersion_);
              remainingWaypointsRouteVersion_ = subBuilder.buildPartial();
            }

            break;
          }
          case 88: {
            int rawValue = input.readEnum();

            view_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return google.maps.fleetengine.v1.TripApi.internal_static_maps_fleetengine_v1_GetTripRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.maps.fleetengine.v1.TripApi.internal_static_maps_fleetengine_v1_GetTripRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.maps.fleetengine.v1.GetTripRequest.class, google.maps.fleetengine.v1.GetTripRequest.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private google.maps.fleetengine.v1.RequestHeader header_;
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   * @return The header.
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.RequestHeader getHeader() {
    return header_ == null ? google.maps.fleetengine.v1.RequestHeader.getDefaultInstance() : header_;
  }
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.RequestHeaderOrBuilder getHeaderOrBuilder() {
    return getHeader();
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * Required. Must be in the format `providers/{provider}/trips/{trip}`.
   * The provider must be the Project ID (for example, `sample-cloud-project`)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * </pre>
   *
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. Must be in the format `providers/{provider}/trips/{trip}`.
   * The provider must be the Project ID (for example, `sample-cloud-project`)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * </pre>
   *
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VIEW_FIELD_NUMBER = 11;
  private int view_;
  /**
   * <pre>
   * The subset of Trip fields that should be returned and their interpretation.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.TripView view = 11;</code>
   * @return The enum numeric value on the wire for view.
   */
  @java.lang.Override public int getViewValue() {
    return view_;
  }
  /**
   * <pre>
   * The subset of Trip fields that should be returned and their interpretation.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.TripView view = 11;</code>
   * @return The view.
   */
  @java.lang.Override public google.maps.fleetengine.v1.TripView getView() {
    @SuppressWarnings("deprecation")
    google.maps.fleetengine.v1.TripView result = google.maps.fleetengine.v1.TripView.valueOf(view_);
    return result == null ? google.maps.fleetengine.v1.TripView.UNRECOGNIZED : result;
  }

  public static final int CURRENT_ROUTE_SEGMENT_VERSION_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp currentRouteSegmentVersion_;
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
   * `Trip.current_route_segment` data are retrieved. If route data are
   * unchanged since this timestamp, the route field is not set in the response.
   * If a minimum is unspecified, the route data are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
   * @return Whether the currentRouteSegmentVersion field is set.
   */
  @java.lang.Override
  public boolean hasCurrentRouteSegmentVersion() {
    return currentRouteSegmentVersion_ != null;
  }
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
   * `Trip.current_route_segment` data are retrieved. If route data are
   * unchanged since this timestamp, the route field is not set in the response.
   * If a minimum is unspecified, the route data are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
   * @return The currentRouteSegmentVersion.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCurrentRouteSegmentVersion() {
    return currentRouteSegmentVersion_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentRouteSegmentVersion_;
  }
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
   * `Trip.current_route_segment` data are retrieved. If route data are
   * unchanged since this timestamp, the route field is not set in the response.
   * If a minimum is unspecified, the route data are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCurrentRouteSegmentVersionOrBuilder() {
    return getCurrentRouteSegmentVersion();
  }

  public static final int REMAINING_WAYPOINTS_VERSION_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp remainingWaypointsVersion_;
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
   * timestamp, the `remaining_waypoints` are not set in the response. If this
   * field is unspecified, `remaining_waypoints` is always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
   * @return Whether the remainingWaypointsVersion field is set.
   */
  @java.lang.Override
  public boolean hasRemainingWaypointsVersion() {
    return remainingWaypointsVersion_ != null;
  }
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
   * timestamp, the `remaining_waypoints` are not set in the response. If this
   * field is unspecified, `remaining_waypoints` is always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
   * @return The remainingWaypointsVersion.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRemainingWaypointsVersion() {
    return remainingWaypointsVersion_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : remainingWaypointsVersion_;
  }
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
   * timestamp, the `remaining_waypoints` are not set in the response. If this
   * field is unspecified, `remaining_waypoints` is always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRemainingWaypointsVersionOrBuilder() {
    return getRemainingWaypointsVersion();
  }

  public static final int ROUTE_FORMAT_TYPE_FIELD_NUMBER = 8;
  private int routeFormatType_;
  /**
   * <pre>
   * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
   * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
   * is `LAT_LNG_LIST_TYPE`.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
   * @return The enum numeric value on the wire for routeFormatType.
   */
  @java.lang.Override public int getRouteFormatTypeValue() {
    return routeFormatType_;
  }
  /**
   * <pre>
   * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
   * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
   * is `LAT_LNG_LIST_TYPE`.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
   * @return The routeFormatType.
   */
  @java.lang.Override public google.maps.fleetengine.v1.PolylineFormatType getRouteFormatType() {
    @SuppressWarnings("deprecation")
    google.maps.fleetengine.v1.PolylineFormatType result = google.maps.fleetengine.v1.PolylineFormatType.valueOf(routeFormatType_);
    return result == null ? google.maps.fleetengine.v1.PolylineFormatType.UNRECOGNIZED : result;
  }

  public static final int CURRENT_ROUTE_SEGMENT_TRAFFIC_VERSION_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp currentRouteSegmentTrafficVersion_;
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
   * unchanged since this timestamp, the `current_route_segment_traffic` field
   * is not set in the response. If a minimum is unspecified, the traffic data
   * are always retrieved. Note that traffic is only available for On-Demand
   * Rides and Deliveries Solution customers.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
   * @return Whether the currentRouteSegmentTrafficVersion field is set.
   */
  @java.lang.Override
  public boolean hasCurrentRouteSegmentTrafficVersion() {
    return currentRouteSegmentTrafficVersion_ != null;
  }
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
   * unchanged since this timestamp, the `current_route_segment_traffic` field
   * is not set in the response. If a minimum is unspecified, the traffic data
   * are always retrieved. Note that traffic is only available for On-Demand
   * Rides and Deliveries Solution customers.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
   * @return The currentRouteSegmentTrafficVersion.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCurrentRouteSegmentTrafficVersion() {
    return currentRouteSegmentTrafficVersion_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentRouteSegmentTrafficVersion_;
  }
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
   * unchanged since this timestamp, the `current_route_segment_traffic` field
   * is not set in the response. If a minimum is unspecified, the traffic data
   * are always retrieved. Note that traffic is only available for On-Demand
   * Rides and Deliveries Solution customers.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCurrentRouteSegmentTrafficVersionOrBuilder() {
    return getCurrentRouteSegmentTrafficVersion();
  }

  public static final int REMAINING_WAYPOINTS_ROUTE_VERSION_FIELD_NUMBER = 10;
  private com.google.protobuf.Timestamp remainingWaypointsRouteVersion_;
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints.traffic_to_waypoint` and
   * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
   * unchanged since this timestamp, the fields above are
   * not set in the response. If `remaining_waypoints_route_version` is
   * unspecified, traffic and path are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
   * @return Whether the remainingWaypointsRouteVersion field is set.
   */
  @java.lang.Override
  public boolean hasRemainingWaypointsRouteVersion() {
    return remainingWaypointsRouteVersion_ != null;
  }
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints.traffic_to_waypoint` and
   * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
   * unchanged since this timestamp, the fields above are
   * not set in the response. If `remaining_waypoints_route_version` is
   * unspecified, traffic and path are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
   * @return The remainingWaypointsRouteVersion.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRemainingWaypointsRouteVersion() {
    return remainingWaypointsRouteVersion_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : remainingWaypointsRouteVersion_;
  }
  /**
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints.traffic_to_waypoint` and
   * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
   * unchanged since this timestamp, the fields above are
   * not set in the response. If `remaining_waypoints_route_version` is
   * unspecified, traffic and path are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRemainingWaypointsRouteVersionOrBuilder() {
    return getRemainingWaypointsRouteVersion();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (currentRouteSegmentVersion_ != null) {
      output.writeMessage(6, getCurrentRouteSegmentVersion());
    }
    if (remainingWaypointsVersion_ != null) {
      output.writeMessage(7, getRemainingWaypointsVersion());
    }
    if (routeFormatType_ != google.maps.fleetengine.v1.PolylineFormatType.UNKNOWN_FORMAT_TYPE.getNumber()) {
      output.writeEnum(8, routeFormatType_);
    }
    if (currentRouteSegmentTrafficVersion_ != null) {
      output.writeMessage(9, getCurrentRouteSegmentTrafficVersion());
    }
    if (remainingWaypointsRouteVersion_ != null) {
      output.writeMessage(10, getRemainingWaypointsRouteVersion());
    }
    if (view_ != google.maps.fleetengine.v1.TripView.TRIP_VIEW_UNSPECIFIED.getNumber()) {
      output.writeEnum(11, view_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (currentRouteSegmentVersion_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCurrentRouteSegmentVersion());
    }
    if (remainingWaypointsVersion_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getRemainingWaypointsVersion());
    }
    if (routeFormatType_ != google.maps.fleetengine.v1.PolylineFormatType.UNKNOWN_FORMAT_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, routeFormatType_);
    }
    if (currentRouteSegmentTrafficVersion_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getCurrentRouteSegmentTrafficVersion());
    }
    if (remainingWaypointsRouteVersion_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getRemainingWaypointsRouteVersion());
    }
    if (view_ != google.maps.fleetengine.v1.TripView.TRIP_VIEW_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, view_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof google.maps.fleetengine.v1.GetTripRequest)) {
      return super.equals(obj);
    }
    google.maps.fleetengine.v1.GetTripRequest other = (google.maps.fleetengine.v1.GetTripRequest) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (!getName()
        .equals(other.getName())) return false;
    if (view_ != other.view_) return false;
    if (hasCurrentRouteSegmentVersion() != other.hasCurrentRouteSegmentVersion()) return false;
    if (hasCurrentRouteSegmentVersion()) {
      if (!getCurrentRouteSegmentVersion()
          .equals(other.getCurrentRouteSegmentVersion())) return false;
    }
    if (hasRemainingWaypointsVersion() != other.hasRemainingWaypointsVersion()) return false;
    if (hasRemainingWaypointsVersion()) {
      if (!getRemainingWaypointsVersion()
          .equals(other.getRemainingWaypointsVersion())) return false;
    }
    if (routeFormatType_ != other.routeFormatType_) return false;
    if (hasCurrentRouteSegmentTrafficVersion() != other.hasCurrentRouteSegmentTrafficVersion()) return false;
    if (hasCurrentRouteSegmentTrafficVersion()) {
      if (!getCurrentRouteSegmentTrafficVersion()
          .equals(other.getCurrentRouteSegmentTrafficVersion())) return false;
    }
    if (hasRemainingWaypointsRouteVersion() != other.hasRemainingWaypointsRouteVersion()) return false;
    if (hasRemainingWaypointsRouteVersion()) {
      if (!getRemainingWaypointsRouteVersion()
          .equals(other.getRemainingWaypointsRouteVersion())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VIEW_FIELD_NUMBER;
    hash = (53 * hash) + view_;
    if (hasCurrentRouteSegmentVersion()) {
      hash = (37 * hash) + CURRENT_ROUTE_SEGMENT_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRouteSegmentVersion().hashCode();
    }
    if (hasRemainingWaypointsVersion()) {
      hash = (37 * hash) + REMAINING_WAYPOINTS_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getRemainingWaypointsVersion().hashCode();
    }
    hash = (37 * hash) + ROUTE_FORMAT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + routeFormatType_;
    if (hasCurrentRouteSegmentTrafficVersion()) {
      hash = (37 * hash) + CURRENT_ROUTE_SEGMENT_TRAFFIC_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRouteSegmentTrafficVersion().hashCode();
    }
    if (hasRemainingWaypointsRouteVersion()) {
      hash = (37 * hash) + REMAINING_WAYPOINTS_ROUTE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getRemainingWaypointsRouteVersion().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(google.maps.fleetengine.v1.GetTripRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * GetTrip request message.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.GetTripRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.GetTripRequest)
      google.maps.fleetengine.v1.GetTripRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.maps.fleetengine.v1.TripApi.internal_static_maps_fleetengine_v1_GetTripRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.maps.fleetengine.v1.TripApi.internal_static_maps_fleetengine_v1_GetTripRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.maps.fleetengine.v1.GetTripRequest.class, google.maps.fleetengine.v1.GetTripRequest.Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.GetTripRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = null;
      } else {
        header_ = null;
        headerBuilder_ = null;
      }
      name_ = "";

      view_ = 0;

      if (currentRouteSegmentVersionBuilder_ == null) {
        currentRouteSegmentVersion_ = null;
      } else {
        currentRouteSegmentVersion_ = null;
        currentRouteSegmentVersionBuilder_ = null;
      }
      if (remainingWaypointsVersionBuilder_ == null) {
        remainingWaypointsVersion_ = null;
      } else {
        remainingWaypointsVersion_ = null;
        remainingWaypointsVersionBuilder_ = null;
      }
      routeFormatType_ = 0;

      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        currentRouteSegmentTrafficVersion_ = null;
      } else {
        currentRouteSegmentTrafficVersion_ = null;
        currentRouteSegmentTrafficVersionBuilder_ = null;
      }
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        remainingWaypointsRouteVersion_ = null;
      } else {
        remainingWaypointsRouteVersion_ = null;
        remainingWaypointsRouteVersionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return google.maps.fleetengine.v1.TripApi.internal_static_maps_fleetengine_v1_GetTripRequest_descriptor;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.GetTripRequest getDefaultInstanceForType() {
      return google.maps.fleetengine.v1.GetTripRequest.getDefaultInstance();
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.GetTripRequest build() {
      google.maps.fleetengine.v1.GetTripRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.GetTripRequest buildPartial() {
      google.maps.fleetengine.v1.GetTripRequest result = new google.maps.fleetengine.v1.GetTripRequest(this);
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.name_ = name_;
      result.view_ = view_;
      if (currentRouteSegmentVersionBuilder_ == null) {
        result.currentRouteSegmentVersion_ = currentRouteSegmentVersion_;
      } else {
        result.currentRouteSegmentVersion_ = currentRouteSegmentVersionBuilder_.build();
      }
      if (remainingWaypointsVersionBuilder_ == null) {
        result.remainingWaypointsVersion_ = remainingWaypointsVersion_;
      } else {
        result.remainingWaypointsVersion_ = remainingWaypointsVersionBuilder_.build();
      }
      result.routeFormatType_ = routeFormatType_;
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        result.currentRouteSegmentTrafficVersion_ = currentRouteSegmentTrafficVersion_;
      } else {
        result.currentRouteSegmentTrafficVersion_ = currentRouteSegmentTrafficVersionBuilder_.build();
      }
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        result.remainingWaypointsRouteVersion_ = remainingWaypointsRouteVersion_;
      } else {
        result.remainingWaypointsRouteVersion_ = remainingWaypointsRouteVersionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.maps.fleetengine.v1.GetTripRequest) {
        return mergeFrom((google.maps.fleetengine.v1.GetTripRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.maps.fleetengine.v1.GetTripRequest other) {
      if (other == google.maps.fleetengine.v1.GetTripRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.view_ != 0) {
        setViewValue(other.getViewValue());
      }
      if (other.hasCurrentRouteSegmentVersion()) {
        mergeCurrentRouteSegmentVersion(other.getCurrentRouteSegmentVersion());
      }
      if (other.hasRemainingWaypointsVersion()) {
        mergeRemainingWaypointsVersion(other.getRemainingWaypointsVersion());
      }
      if (other.routeFormatType_ != 0) {
        setRouteFormatTypeValue(other.getRouteFormatTypeValue());
      }
      if (other.hasCurrentRouteSegmentTrafficVersion()) {
        mergeCurrentRouteSegmentTrafficVersion(other.getCurrentRouteSegmentTrafficVersion());
      }
      if (other.hasRemainingWaypointsRouteVersion()) {
        mergeRemainingWaypointsRouteVersion(other.getRemainingWaypointsRouteVersion());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      google.maps.fleetengine.v1.GetTripRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (google.maps.fleetengine.v1.GetTripRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private google.maps.fleetengine.v1.RequestHeader header_;
    private com.google.protobuf.SingleFieldBuilderV3<
        google.maps.fleetengine.v1.RequestHeader, google.maps.fleetengine.v1.RequestHeader.Builder, google.maps.fleetengine.v1.RequestHeaderOrBuilder> headerBuilder_;
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return headerBuilder_ != null || header_ != null;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     * @return The header.
     */
    public google.maps.fleetengine.v1.RequestHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? google.maps.fleetengine.v1.RequestHeader.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder setHeader(google.maps.fleetengine.v1.RequestHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder setHeader(
        google.maps.fleetengine.v1.RequestHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder mergeHeader(google.maps.fleetengine.v1.RequestHeader value) {
      if (headerBuilder_ == null) {
        if (header_ != null) {
          header_ =
            google.maps.fleetengine.v1.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = null;
        onChanged();
      } else {
        header_ = null;
        headerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public google.maps.fleetengine.v1.RequestHeader.Builder getHeaderBuilder() {
      
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public google.maps.fleetengine.v1.RequestHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            google.maps.fleetengine.v1.RequestHeader.getDefaultInstance() : header_;
      }
    }
    /**
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        google.maps.fleetengine.v1.RequestHeader, google.maps.fleetengine.v1.RequestHeader.Builder, google.maps.fleetengine.v1.RequestHeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            google.maps.fleetengine.v1.RequestHeader, google.maps.fleetengine.v1.RequestHeader.Builder, google.maps.fleetengine.v1.RequestHeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int view_ = 0;
    /**
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     * @return The enum numeric value on the wire for view.
     */
    @java.lang.Override public int getViewValue() {
      return view_;
    }
    /**
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     * @param value The enum numeric value on the wire for view to set.
     * @return This builder for chaining.
     */
    public Builder setViewValue(int value) {
      
      view_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     * @return The view.
     */
    @java.lang.Override
    public google.maps.fleetengine.v1.TripView getView() {
      @SuppressWarnings("deprecation")
      google.maps.fleetengine.v1.TripView result = google.maps.fleetengine.v1.TripView.valueOf(view_);
      return result == null ? google.maps.fleetengine.v1.TripView.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     * @param value The view to set.
     * @return This builder for chaining.
     */
    public Builder setView(google.maps.fleetengine.v1.TripView value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      view_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearView() {
      
      view_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp currentRouteSegmentVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> currentRouteSegmentVersionBuilder_;
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     * @return Whether the currentRouteSegmentVersion field is set.
     */
    public boolean hasCurrentRouteSegmentVersion() {
      return currentRouteSegmentVersionBuilder_ != null || currentRouteSegmentVersion_ != null;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     * @return The currentRouteSegmentVersion.
     */
    public com.google.protobuf.Timestamp getCurrentRouteSegmentVersion() {
      if (currentRouteSegmentVersionBuilder_ == null) {
        return currentRouteSegmentVersion_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentRouteSegmentVersion_;
      } else {
        return currentRouteSegmentVersionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public Builder setCurrentRouteSegmentVersion(com.google.protobuf.Timestamp value) {
      if (currentRouteSegmentVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentRouteSegmentVersion_ = value;
        onChanged();
      } else {
        currentRouteSegmentVersionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public Builder setCurrentRouteSegmentVersion(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (currentRouteSegmentVersionBuilder_ == null) {
        currentRouteSegmentVersion_ = builderForValue.build();
        onChanged();
      } else {
        currentRouteSegmentVersionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public Builder mergeCurrentRouteSegmentVersion(com.google.protobuf.Timestamp value) {
      if (currentRouteSegmentVersionBuilder_ == null) {
        if (currentRouteSegmentVersion_ != null) {
          currentRouteSegmentVersion_ =
            com.google.protobuf.Timestamp.newBuilder(currentRouteSegmentVersion_).mergeFrom(value).buildPartial();
        } else {
          currentRouteSegmentVersion_ = value;
        }
        onChanged();
      } else {
        currentRouteSegmentVersionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public Builder clearCurrentRouteSegmentVersion() {
      if (currentRouteSegmentVersionBuilder_ == null) {
        currentRouteSegmentVersion_ = null;
        onChanged();
      } else {
        currentRouteSegmentVersion_ = null;
        currentRouteSegmentVersionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCurrentRouteSegmentVersionBuilder() {
      
      onChanged();
      return getCurrentRouteSegmentVersionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCurrentRouteSegmentVersionOrBuilder() {
      if (currentRouteSegmentVersionBuilder_ != null) {
        return currentRouteSegmentVersionBuilder_.getMessageOrBuilder();
      } else {
        return currentRouteSegmentVersion_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : currentRouteSegmentVersion_;
      }
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCurrentRouteSegmentVersionFieldBuilder() {
      if (currentRouteSegmentVersionBuilder_ == null) {
        currentRouteSegmentVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCurrentRouteSegmentVersion(),
                getParentForChildren(),
                isClean());
        currentRouteSegmentVersion_ = null;
      }
      return currentRouteSegmentVersionBuilder_;
    }

    private com.google.protobuf.Timestamp remainingWaypointsVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> remainingWaypointsVersionBuilder_;
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     * @return Whether the remainingWaypointsVersion field is set.
     */
    public boolean hasRemainingWaypointsVersion() {
      return remainingWaypointsVersionBuilder_ != null || remainingWaypointsVersion_ != null;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     * @return The remainingWaypointsVersion.
     */
    public com.google.protobuf.Timestamp getRemainingWaypointsVersion() {
      if (remainingWaypointsVersionBuilder_ == null) {
        return remainingWaypointsVersion_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : remainingWaypointsVersion_;
      } else {
        return remainingWaypointsVersionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public Builder setRemainingWaypointsVersion(com.google.protobuf.Timestamp value) {
      if (remainingWaypointsVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        remainingWaypointsVersion_ = value;
        onChanged();
      } else {
        remainingWaypointsVersionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public Builder setRemainingWaypointsVersion(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (remainingWaypointsVersionBuilder_ == null) {
        remainingWaypointsVersion_ = builderForValue.build();
        onChanged();
      } else {
        remainingWaypointsVersionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public Builder mergeRemainingWaypointsVersion(com.google.protobuf.Timestamp value) {
      if (remainingWaypointsVersionBuilder_ == null) {
        if (remainingWaypointsVersion_ != null) {
          remainingWaypointsVersion_ =
            com.google.protobuf.Timestamp.newBuilder(remainingWaypointsVersion_).mergeFrom(value).buildPartial();
        } else {
          remainingWaypointsVersion_ = value;
        }
        onChanged();
      } else {
        remainingWaypointsVersionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public Builder clearRemainingWaypointsVersion() {
      if (remainingWaypointsVersionBuilder_ == null) {
        remainingWaypointsVersion_ = null;
        onChanged();
      } else {
        remainingWaypointsVersion_ = null;
        remainingWaypointsVersionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getRemainingWaypointsVersionBuilder() {
      
      onChanged();
      return getRemainingWaypointsVersionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRemainingWaypointsVersionOrBuilder() {
      if (remainingWaypointsVersionBuilder_ != null) {
        return remainingWaypointsVersionBuilder_.getMessageOrBuilder();
      } else {
        return remainingWaypointsVersion_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : remainingWaypointsVersion_;
      }
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getRemainingWaypointsVersionFieldBuilder() {
      if (remainingWaypointsVersionBuilder_ == null) {
        remainingWaypointsVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRemainingWaypointsVersion(),
                getParentForChildren(),
                isClean());
        remainingWaypointsVersion_ = null;
      }
      return remainingWaypointsVersionBuilder_;
    }

    private int routeFormatType_ = 0;
    /**
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     * @return The enum numeric value on the wire for routeFormatType.
     */
    @java.lang.Override public int getRouteFormatTypeValue() {
      return routeFormatType_;
    }
    /**
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     * @param value The enum numeric value on the wire for routeFormatType to set.
     * @return This builder for chaining.
     */
    public Builder setRouteFormatTypeValue(int value) {
      
      routeFormatType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     * @return The routeFormatType.
     */
    @java.lang.Override
    public google.maps.fleetengine.v1.PolylineFormatType getRouteFormatType() {
      @SuppressWarnings("deprecation")
      google.maps.fleetengine.v1.PolylineFormatType result = google.maps.fleetengine.v1.PolylineFormatType.valueOf(routeFormatType_);
      return result == null ? google.maps.fleetengine.v1.PolylineFormatType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     * @param value The routeFormatType to set.
     * @return This builder for chaining.
     */
    public Builder setRouteFormatType(google.maps.fleetengine.v1.PolylineFormatType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      routeFormatType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRouteFormatType() {
      
      routeFormatType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp currentRouteSegmentTrafficVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> currentRouteSegmentTrafficVersionBuilder_;
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     * @return Whether the currentRouteSegmentTrafficVersion field is set.
     */
    public boolean hasCurrentRouteSegmentTrafficVersion() {
      return currentRouteSegmentTrafficVersionBuilder_ != null || currentRouteSegmentTrafficVersion_ != null;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     * @return The currentRouteSegmentTrafficVersion.
     */
    public com.google.protobuf.Timestamp getCurrentRouteSegmentTrafficVersion() {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        return currentRouteSegmentTrafficVersion_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentRouteSegmentTrafficVersion_;
      } else {
        return currentRouteSegmentTrafficVersionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public Builder setCurrentRouteSegmentTrafficVersion(com.google.protobuf.Timestamp value) {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentRouteSegmentTrafficVersion_ = value;
        onChanged();
      } else {
        currentRouteSegmentTrafficVersionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public Builder setCurrentRouteSegmentTrafficVersion(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        currentRouteSegmentTrafficVersion_ = builderForValue.build();
        onChanged();
      } else {
        currentRouteSegmentTrafficVersionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public Builder mergeCurrentRouteSegmentTrafficVersion(com.google.protobuf.Timestamp value) {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        if (currentRouteSegmentTrafficVersion_ != null) {
          currentRouteSegmentTrafficVersion_ =
            com.google.protobuf.Timestamp.newBuilder(currentRouteSegmentTrafficVersion_).mergeFrom(value).buildPartial();
        } else {
          currentRouteSegmentTrafficVersion_ = value;
        }
        onChanged();
      } else {
        currentRouteSegmentTrafficVersionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public Builder clearCurrentRouteSegmentTrafficVersion() {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        currentRouteSegmentTrafficVersion_ = null;
        onChanged();
      } else {
        currentRouteSegmentTrafficVersion_ = null;
        currentRouteSegmentTrafficVersionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCurrentRouteSegmentTrafficVersionBuilder() {
      
      onChanged();
      return getCurrentRouteSegmentTrafficVersionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCurrentRouteSegmentTrafficVersionOrBuilder() {
      if (currentRouteSegmentTrafficVersionBuilder_ != null) {
        return currentRouteSegmentTrafficVersionBuilder_.getMessageOrBuilder();
      } else {
        return currentRouteSegmentTrafficVersion_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : currentRouteSegmentTrafficVersion_;
      }
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCurrentRouteSegmentTrafficVersionFieldBuilder() {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        currentRouteSegmentTrafficVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCurrentRouteSegmentTrafficVersion(),
                getParentForChildren(),
                isClean());
        currentRouteSegmentTrafficVersion_ = null;
      }
      return currentRouteSegmentTrafficVersionBuilder_;
    }

    private com.google.protobuf.Timestamp remainingWaypointsRouteVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> remainingWaypointsRouteVersionBuilder_;
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     * @return Whether the remainingWaypointsRouteVersion field is set.
     */
    public boolean hasRemainingWaypointsRouteVersion() {
      return remainingWaypointsRouteVersionBuilder_ != null || remainingWaypointsRouteVersion_ != null;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     * @return The remainingWaypointsRouteVersion.
     */
    public com.google.protobuf.Timestamp getRemainingWaypointsRouteVersion() {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        return remainingWaypointsRouteVersion_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : remainingWaypointsRouteVersion_;
      } else {
        return remainingWaypointsRouteVersionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public Builder setRemainingWaypointsRouteVersion(com.google.protobuf.Timestamp value) {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        remainingWaypointsRouteVersion_ = value;
        onChanged();
      } else {
        remainingWaypointsRouteVersionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public Builder setRemainingWaypointsRouteVersion(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        remainingWaypointsRouteVersion_ = builderForValue.build();
        onChanged();
      } else {
        remainingWaypointsRouteVersionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public Builder mergeRemainingWaypointsRouteVersion(com.google.protobuf.Timestamp value) {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        if (remainingWaypointsRouteVersion_ != null) {
          remainingWaypointsRouteVersion_ =
            com.google.protobuf.Timestamp.newBuilder(remainingWaypointsRouteVersion_).mergeFrom(value).buildPartial();
        } else {
          remainingWaypointsRouteVersion_ = value;
        }
        onChanged();
      } else {
        remainingWaypointsRouteVersionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public Builder clearRemainingWaypointsRouteVersion() {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        remainingWaypointsRouteVersion_ = null;
        onChanged();
      } else {
        remainingWaypointsRouteVersion_ = null;
        remainingWaypointsRouteVersionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public com.google.protobuf.Timestamp.Builder getRemainingWaypointsRouteVersionBuilder() {
      
      onChanged();
      return getRemainingWaypointsRouteVersionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRemainingWaypointsRouteVersionOrBuilder() {
      if (remainingWaypointsRouteVersionBuilder_ != null) {
        return remainingWaypointsRouteVersionBuilder_.getMessageOrBuilder();
      } else {
        return remainingWaypointsRouteVersion_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : remainingWaypointsRouteVersion_;
      }
    }
    /**
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getRemainingWaypointsRouteVersionFieldBuilder() {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        remainingWaypointsRouteVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRemainingWaypointsRouteVersion(),
                getParentForChildren(),
                isClean());
        remainingWaypointsRouteVersion_ = null;
      }
      return remainingWaypointsRouteVersionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.GetTripRequest)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.GetTripRequest)
  private static final google.maps.fleetengine.v1.GetTripRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new google.maps.fleetengine.v1.GetTripRequest();
  }

  public static google.maps.fleetengine.v1.GetTripRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTripRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetTripRequest>() {
    @java.lang.Override
    public GetTripRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTripRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTripRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTripRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.maps.fleetengine.v1.GetTripRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

