// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/header.proto

package google.maps.fleetengine.v1;

/**
 * <pre>
 * A RequestHeader contains fields common to all Fleet Engine RPC requests.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.RequestHeader}
 */
public final class RequestHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.RequestHeader)
    RequestHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestHeader.newBuilder() to construct.
  private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestHeader() {
    languageCode_ = "";
    regionCode_ = "";
    sdkVersion_ = "";
    osVersion_ = "";
    deviceModel_ = "";
    sdkType_ = 0;
    mapsSdkVersion_ = "";
    navSdkVersion_ = "";
    platform_ = 0;
    manufacturer_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestHeader();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            languageCode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            regionCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            sdkVersion_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            osVersion_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceModel_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            sdkType_ = rawValue;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            mapsSdkVersion_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            navSdkVersion_ = s;
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            platform_ = rawValue;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            manufacturer_ = s;
            break;
          }
          case 88: {

            androidApiLevel_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return google.maps.fleetengine.v1.Headers.internal_static_maps_fleetengine_v1_RequestHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.maps.fleetengine.v1.Headers.internal_static_maps_fleetengine_v1_RequestHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.maps.fleetengine.v1.RequestHeader.class, google.maps.fleetengine.v1.RequestHeader.Builder.class);
  }

  /**
   * <pre>
   * Possible types of SDK.
   * </pre>
   *
   * Protobuf enum {@code maps.fleetengine.v1.RequestHeader.SdkType}
   */
  public enum SdkType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The default value. This value is used if the `sdk_type` is omitted.
     * </pre>
     *
     * <code>SDK_TYPE_UNSPECIFIED = 0;</code>
     */
    SDK_TYPE_UNSPECIFIED(0),
    /**
     * <pre>
     * The calling SDK is Consumer.
     * </pre>
     *
     * <code>CONSUMER = 1;</code>
     */
    CONSUMER(1),
    /**
     * <pre>
     * The calling SDK is Driver.
     * </pre>
     *
     * <code>DRIVER = 2;</code>
     */
    DRIVER(2),
    /**
     * <pre>
     * The calling SDK is JavaScript.
     * </pre>
     *
     * <code>JAVASCRIPT = 3;</code>
     */
    JAVASCRIPT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The default value. This value is used if the `sdk_type` is omitted.
     * </pre>
     *
     * <code>SDK_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int SDK_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * The calling SDK is Consumer.
     * </pre>
     *
     * <code>CONSUMER = 1;</code>
     */
    public static final int CONSUMER_VALUE = 1;
    /**
     * <pre>
     * The calling SDK is Driver.
     * </pre>
     *
     * <code>DRIVER = 2;</code>
     */
    public static final int DRIVER_VALUE = 2;
    /**
     * <pre>
     * The calling SDK is JavaScript.
     * </pre>
     *
     * <code>JAVASCRIPT = 3;</code>
     */
    public static final int JAVASCRIPT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SdkType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SdkType forNumber(int value) {
      switch (value) {
        case 0: return SDK_TYPE_UNSPECIFIED;
        case 1: return CONSUMER;
        case 2: return DRIVER;
        case 3: return JAVASCRIPT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SdkType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SdkType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SdkType>() {
            public SdkType findValueByNumber(int number) {
              return SdkType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return google.maps.fleetengine.v1.RequestHeader.getDescriptor().getEnumTypes().get(0);
    }

    private static final SdkType[] VALUES = values();

    public static SdkType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SdkType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maps.fleetengine.v1.RequestHeader.SdkType)
  }

  /**
   * <pre>
   * The platform of the calling SDK.
   * </pre>
   *
   * Protobuf enum {@code maps.fleetengine.v1.RequestHeader.Platform}
   */
  public enum Platform
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The default value. This value is used if the platform is omitted.
     * </pre>
     *
     * <code>PLATFORM_UNSPECIFIED = 0;</code>
     */
    PLATFORM_UNSPECIFIED(0),
    /**
     * <pre>
     * The request is coming from Android.
     * </pre>
     *
     * <code>ANDROID = 1;</code>
     */
    ANDROID(1),
    /**
     * <pre>
     * The request is coming from iOS.
     * </pre>
     *
     * <code>IOS = 2;</code>
     */
    IOS(2),
    /**
     * <pre>
     * The request is coming from the web.
     * </pre>
     *
     * <code>WEB = 3;</code>
     */
    WEB(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The default value. This value is used if the platform is omitted.
     * </pre>
     *
     * <code>PLATFORM_UNSPECIFIED = 0;</code>
     */
    public static final int PLATFORM_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * The request is coming from Android.
     * </pre>
     *
     * <code>ANDROID = 1;</code>
     */
    public static final int ANDROID_VALUE = 1;
    /**
     * <pre>
     * The request is coming from iOS.
     * </pre>
     *
     * <code>IOS = 2;</code>
     */
    public static final int IOS_VALUE = 2;
    /**
     * <pre>
     * The request is coming from the web.
     * </pre>
     *
     * <code>WEB = 3;</code>
     */
    public static final int WEB_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Platform valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Platform forNumber(int value) {
      switch (value) {
        case 0: return PLATFORM_UNSPECIFIED;
        case 1: return ANDROID;
        case 2: return IOS;
        case 3: return WEB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Platform>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Platform> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Platform>() {
            public Platform findValueByNumber(int number) {
              return Platform.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return google.maps.fleetengine.v1.RequestHeader.getDescriptor().getEnumTypes().get(1);
    }

    private static final Platform[] VALUES = values();

    public static Platform valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Platform(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maps.fleetengine.v1.RequestHeader.Platform)
  }

  public static final int LANGUAGE_CODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object languageCode_;
  /**
   * <pre>
   * The BCP-47 language code, such as en-US or sr-Latn. For more information,
   * see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. If none
   * is specified, the response may be in any language, with a preference for
   * English if such a name exists. Field value example: `en-US`.
   * </pre>
   *
   * <code>string language_code = 1;</code>
   * @return The languageCode.
   */
  @java.lang.Override
  public java.lang.String getLanguageCode() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languageCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The BCP-47 language code, such as en-US or sr-Latn. For more information,
   * see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. If none
   * is specified, the response may be in any language, with a preference for
   * English if such a name exists. Field value example: `en-US`.
   * </pre>
   *
   * <code>string language_code = 1;</code>
   * @return The bytes for languageCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageCodeBytes() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languageCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGION_CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object regionCode_;
  /**
   * <pre>
   * Required. CLDR region code of the region where the request originates.
   * Field value example: `US`.
   * </pre>
   *
   * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The regionCode.
   */
  @java.lang.Override
  public java.lang.String getRegionCode() {
    java.lang.Object ref = regionCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      regionCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Required. CLDR region code of the region where the request originates.
   * Field value example: `US`.
   * </pre>
   *
   * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for regionCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegionCodeBytes() {
    java.lang.Object ref = regionCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      regionCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SDK_VERSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object sdkVersion_;
  /**
   * <pre>
   * Version of the calling SDK, if applicable.
   * The version format is "major.minor.patch", example: `1.1.2`.
   * </pre>
   *
   * <code>string sdk_version = 3;</code>
   * @return The sdkVersion.
   */
  @java.lang.Override
  public java.lang.String getSdkVersion() {
    java.lang.Object ref = sdkVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sdkVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version of the calling SDK, if applicable.
   * The version format is "major.minor.patch", example: `1.1.2`.
   * </pre>
   *
   * <code>string sdk_version = 3;</code>
   * @return The bytes for sdkVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSdkVersionBytes() {
    java.lang.Object ref = sdkVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sdkVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_VERSION_FIELD_NUMBER = 4;
  private volatile java.lang.Object osVersion_;
  /**
   * <pre>
   * Version of the operating system on which the calling SDK is running.
   * Field value examples: `4.4.1`, `12.1`.
   * </pre>
   *
   * <code>string os_version = 4;</code>
   * @return The osVersion.
   */
  @java.lang.Override
  public java.lang.String getOsVersion() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version of the operating system on which the calling SDK is running.
   * Field value examples: `4.4.1`, `12.1`.
   * </pre>
   *
   * <code>string os_version = 4;</code>
   * @return The bytes for osVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsVersionBytes() {
    java.lang.Object ref = osVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_MODEL_FIELD_NUMBER = 5;
  private volatile java.lang.Object deviceModel_;
  /**
   * <pre>
   * Model of the device on which the calling SDK is running.
   * Field value examples: `iPhone12,1`, `SM-G920F`.
   * </pre>
   *
   * <code>string device_model = 5;</code>
   * @return The deviceModel.
   */
  @java.lang.Override
  public java.lang.String getDeviceModel() {
    java.lang.Object ref = deviceModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceModel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Model of the device on which the calling SDK is running.
   * Field value examples: `iPhone12,1`, `SM-G920F`.
   * </pre>
   *
   * <code>string device_model = 5;</code>
   * @return The bytes for deviceModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceModelBytes() {
    java.lang.Object ref = deviceModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SDK_TYPE_FIELD_NUMBER = 6;
  private int sdkType_;
  /**
   * <pre>
   * The type of SDK sending the request.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader.SdkType sdk_type = 6;</code>
   * @return The enum numeric value on the wire for sdkType.
   */
  @java.lang.Override public int getSdkTypeValue() {
    return sdkType_;
  }
  /**
   * <pre>
   * The type of SDK sending the request.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader.SdkType sdk_type = 6;</code>
   * @return The sdkType.
   */
  @java.lang.Override public google.maps.fleetengine.v1.RequestHeader.SdkType getSdkType() {
    @SuppressWarnings("deprecation")
    google.maps.fleetengine.v1.RequestHeader.SdkType result = google.maps.fleetengine.v1.RequestHeader.SdkType.valueOf(sdkType_);
    return result == null ? google.maps.fleetengine.v1.RequestHeader.SdkType.UNRECOGNIZED : result;
  }

  public static final int MAPS_SDK_VERSION_FIELD_NUMBER = 7;
  private volatile java.lang.Object mapsSdkVersion_;
  /**
   * <pre>
   * Version of the MapSDK which the calling SDK depends on, if applicable.
   * The version format is "major.minor.patch", example: `5.2.1`.
   * </pre>
   *
   * <code>string maps_sdk_version = 7;</code>
   * @return The mapsSdkVersion.
   */
  @java.lang.Override
  public java.lang.String getMapsSdkVersion() {
    java.lang.Object ref = mapsSdkVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mapsSdkVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version of the MapSDK which the calling SDK depends on, if applicable.
   * The version format is "major.minor.patch", example: `5.2.1`.
   * </pre>
   *
   * <code>string maps_sdk_version = 7;</code>
   * @return The bytes for mapsSdkVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMapsSdkVersionBytes() {
    java.lang.Object ref = mapsSdkVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mapsSdkVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAV_SDK_VERSION_FIELD_NUMBER = 8;
  private volatile java.lang.Object navSdkVersion_;
  /**
   * <pre>
   * Version of the NavSDK which the calling SDK depends on, if applicable.
   * The version format is "major.minor.patch", example: `2.1.0`.
   * </pre>
   *
   * <code>string nav_sdk_version = 8;</code>
   * @return The navSdkVersion.
   */
  @java.lang.Override
  public java.lang.String getNavSdkVersion() {
    java.lang.Object ref = navSdkVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      navSdkVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Version of the NavSDK which the calling SDK depends on, if applicable.
   * The version format is "major.minor.patch", example: `2.1.0`.
   * </pre>
   *
   * <code>string nav_sdk_version = 8;</code>
   * @return The bytes for navSdkVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNavSdkVersionBytes() {
    java.lang.Object ref = navSdkVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      navSdkVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_FIELD_NUMBER = 9;
  private int platform_;
  /**
   * <pre>
   * Platform of the calling SDK.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader.Platform platform = 9;</code>
   * @return The enum numeric value on the wire for platform.
   */
  @java.lang.Override public int getPlatformValue() {
    return platform_;
  }
  /**
   * <pre>
   * Platform of the calling SDK.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader.Platform platform = 9;</code>
   * @return The platform.
   */
  @java.lang.Override public google.maps.fleetengine.v1.RequestHeader.Platform getPlatform() {
    @SuppressWarnings("deprecation")
    google.maps.fleetengine.v1.RequestHeader.Platform result = google.maps.fleetengine.v1.RequestHeader.Platform.valueOf(platform_);
    return result == null ? google.maps.fleetengine.v1.RequestHeader.Platform.UNRECOGNIZED : result;
  }

  public static final int MANUFACTURER_FIELD_NUMBER = 10;
  private volatile java.lang.Object manufacturer_;
  /**
   * <pre>
   * Manufacturer of the Android device from the calling SDK, only applicable
   * for the Android SDKs.
   * Field value example: `Samsung`.
   * </pre>
   *
   * <code>string manufacturer = 10;</code>
   * @return The manufacturer.
   */
  @java.lang.Override
  public java.lang.String getManufacturer() {
    java.lang.Object ref = manufacturer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      manufacturer_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Manufacturer of the Android device from the calling SDK, only applicable
   * for the Android SDKs.
   * Field value example: `Samsung`.
   * </pre>
   *
   * <code>string manufacturer = 10;</code>
   * @return The bytes for manufacturer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getManufacturerBytes() {
    java.lang.Object ref = manufacturer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      manufacturer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANDROID_API_LEVEL_FIELD_NUMBER = 11;
  private int androidApiLevel_;
  /**
   * <pre>
   * Android API level of the calling SDK, only applicable for the Android SDKs.
   * Field value example: `23`.
   * </pre>
   *
   * <code>int32 android_api_level = 11;</code>
   * @return The androidApiLevel.
   */
  @java.lang.Override
  public int getAndroidApiLevel() {
    return androidApiLevel_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languageCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, languageCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(regionCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, regionCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sdkVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sdkVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, osVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceModel_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceModel_);
    }
    if (sdkType_ != google.maps.fleetengine.v1.RequestHeader.SdkType.SDK_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(6, sdkType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mapsSdkVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, mapsSdkVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(navSdkVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, navSdkVersion_);
    }
    if (platform_ != google.maps.fleetengine.v1.RequestHeader.Platform.PLATFORM_UNSPECIFIED.getNumber()) {
      output.writeEnum(9, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(manufacturer_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, manufacturer_);
    }
    if (androidApiLevel_ != 0) {
      output.writeInt32(11, androidApiLevel_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languageCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, languageCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(regionCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, regionCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sdkVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sdkVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, osVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceModel_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceModel_);
    }
    if (sdkType_ != google.maps.fleetengine.v1.RequestHeader.SdkType.SDK_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, sdkType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mapsSdkVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, mapsSdkVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(navSdkVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, navSdkVersion_);
    }
    if (platform_ != google.maps.fleetengine.v1.RequestHeader.Platform.PLATFORM_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, platform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(manufacturer_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, manufacturer_);
    }
    if (androidApiLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, androidApiLevel_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof google.maps.fleetengine.v1.RequestHeader)) {
      return super.equals(obj);
    }
    google.maps.fleetengine.v1.RequestHeader other = (google.maps.fleetengine.v1.RequestHeader) obj;

    if (!getLanguageCode()
        .equals(other.getLanguageCode())) return false;
    if (!getRegionCode()
        .equals(other.getRegionCode())) return false;
    if (!getSdkVersion()
        .equals(other.getSdkVersion())) return false;
    if (!getOsVersion()
        .equals(other.getOsVersion())) return false;
    if (!getDeviceModel()
        .equals(other.getDeviceModel())) return false;
    if (sdkType_ != other.sdkType_) return false;
    if (!getMapsSdkVersion()
        .equals(other.getMapsSdkVersion())) return false;
    if (!getNavSdkVersion()
        .equals(other.getNavSdkVersion())) return false;
    if (platform_ != other.platform_) return false;
    if (!getManufacturer()
        .equals(other.getManufacturer())) return false;
    if (getAndroidApiLevel()
        != other.getAndroidApiLevel()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LANGUAGE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguageCode().hashCode();
    hash = (37 * hash) + REGION_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRegionCode().hashCode();
    hash = (37 * hash) + SDK_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getSdkVersion().hashCode();
    hash = (37 * hash) + OS_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getOsVersion().hashCode();
    hash = (37 * hash) + DEVICE_MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceModel().hashCode();
    hash = (37 * hash) + SDK_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + sdkType_;
    hash = (37 * hash) + MAPS_SDK_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getMapsSdkVersion().hashCode();
    hash = (37 * hash) + NAV_SDK_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getNavSdkVersion().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + platform_;
    hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
    hash = (53 * hash) + getManufacturer().hashCode();
    hash = (37 * hash) + ANDROID_API_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getAndroidApiLevel();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.maps.fleetengine.v1.RequestHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.maps.fleetengine.v1.RequestHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(google.maps.fleetengine.v1.RequestHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A RequestHeader contains fields common to all Fleet Engine RPC requests.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.RequestHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.RequestHeader)
      google.maps.fleetengine.v1.RequestHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.maps.fleetengine.v1.Headers.internal_static_maps_fleetengine_v1_RequestHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.maps.fleetengine.v1.Headers.internal_static_maps_fleetengine_v1_RequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.maps.fleetengine.v1.RequestHeader.class, google.maps.fleetengine.v1.RequestHeader.Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.RequestHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      languageCode_ = "";

      regionCode_ = "";

      sdkVersion_ = "";

      osVersion_ = "";

      deviceModel_ = "";

      sdkType_ = 0;

      mapsSdkVersion_ = "";

      navSdkVersion_ = "";

      platform_ = 0;

      manufacturer_ = "";

      androidApiLevel_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return google.maps.fleetengine.v1.Headers.internal_static_maps_fleetengine_v1_RequestHeader_descriptor;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.RequestHeader getDefaultInstanceForType() {
      return google.maps.fleetengine.v1.RequestHeader.getDefaultInstance();
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.RequestHeader build() {
      google.maps.fleetengine.v1.RequestHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.RequestHeader buildPartial() {
      google.maps.fleetengine.v1.RequestHeader result = new google.maps.fleetengine.v1.RequestHeader(this);
      result.languageCode_ = languageCode_;
      result.regionCode_ = regionCode_;
      result.sdkVersion_ = sdkVersion_;
      result.osVersion_ = osVersion_;
      result.deviceModel_ = deviceModel_;
      result.sdkType_ = sdkType_;
      result.mapsSdkVersion_ = mapsSdkVersion_;
      result.navSdkVersion_ = navSdkVersion_;
      result.platform_ = platform_;
      result.manufacturer_ = manufacturer_;
      result.androidApiLevel_ = androidApiLevel_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.maps.fleetengine.v1.RequestHeader) {
        return mergeFrom((google.maps.fleetengine.v1.RequestHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.maps.fleetengine.v1.RequestHeader other) {
      if (other == google.maps.fleetengine.v1.RequestHeader.getDefaultInstance()) return this;
      if (!other.getLanguageCode().isEmpty()) {
        languageCode_ = other.languageCode_;
        onChanged();
      }
      if (!other.getRegionCode().isEmpty()) {
        regionCode_ = other.regionCode_;
        onChanged();
      }
      if (!other.getSdkVersion().isEmpty()) {
        sdkVersion_ = other.sdkVersion_;
        onChanged();
      }
      if (!other.getOsVersion().isEmpty()) {
        osVersion_ = other.osVersion_;
        onChanged();
      }
      if (!other.getDeviceModel().isEmpty()) {
        deviceModel_ = other.deviceModel_;
        onChanged();
      }
      if (other.sdkType_ != 0) {
        setSdkTypeValue(other.getSdkTypeValue());
      }
      if (!other.getMapsSdkVersion().isEmpty()) {
        mapsSdkVersion_ = other.mapsSdkVersion_;
        onChanged();
      }
      if (!other.getNavSdkVersion().isEmpty()) {
        navSdkVersion_ = other.navSdkVersion_;
        onChanged();
      }
      if (other.platform_ != 0) {
        setPlatformValue(other.getPlatformValue());
      }
      if (!other.getManufacturer().isEmpty()) {
        manufacturer_ = other.manufacturer_;
        onChanged();
      }
      if (other.getAndroidApiLevel() != 0) {
        setAndroidApiLevel(other.getAndroidApiLevel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      google.maps.fleetengine.v1.RequestHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (google.maps.fleetengine.v1.RequestHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object languageCode_ = "";
    /**
     * <pre>
     * The BCP-47 language code, such as en-US or sr-Latn. For more information,
     * see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. If none
     * is specified, the response may be in any language, with a preference for
     * English if such a name exists. Field value example: `en-US`.
     * </pre>
     *
     * <code>string language_code = 1;</code>
     * @return The languageCode.
     */
    public java.lang.String getLanguageCode() {
      java.lang.Object ref = languageCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The BCP-47 language code, such as en-US or sr-Latn. For more information,
     * see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. If none
     * is specified, the response may be in any language, with a preference for
     * English if such a name exists. Field value example: `en-US`.
     * </pre>
     *
     * <code>string language_code = 1;</code>
     * @return The bytes for languageCode.
     */
    public com.google.protobuf.ByteString
        getLanguageCodeBytes() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The BCP-47 language code, such as en-US or sr-Latn. For more information,
     * see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. If none
     * is specified, the response may be in any language, with a preference for
     * English if such a name exists. Field value example: `en-US`.
     * </pre>
     *
     * <code>string language_code = 1;</code>
     * @param value The languageCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      languageCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The BCP-47 language code, such as en-US or sr-Latn. For more information,
     * see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. If none
     * is specified, the response may be in any language, with a preference for
     * English if such a name exists. Field value example: `en-US`.
     * </pre>
     *
     * <code>string language_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguageCode() {
      
      languageCode_ = getDefaultInstance().getLanguageCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The BCP-47 language code, such as en-US or sr-Latn. For more information,
     * see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. If none
     * is specified, the response may be in any language, with a preference for
     * English if such a name exists. Field value example: `en-US`.
     * </pre>
     *
     * <code>string language_code = 1;</code>
     * @param value The bytes for languageCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      languageCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object regionCode_ = "";
    /**
     * <pre>
     * Required. CLDR region code of the region where the request originates.
     * Field value example: `US`.
     * </pre>
     *
     * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The regionCode.
     */
    public java.lang.String getRegionCode() {
      java.lang.Object ref = regionCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        regionCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Required. CLDR region code of the region where the request originates.
     * Field value example: `US`.
     * </pre>
     *
     * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for regionCode.
     */
    public com.google.protobuf.ByteString
        getRegionCodeBytes() {
      java.lang.Object ref = regionCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regionCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Required. CLDR region code of the region where the request originates.
     * Field value example: `US`.
     * </pre>
     *
     * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The regionCode to set.
     * @return This builder for chaining.
     */
    public Builder setRegionCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      regionCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. CLDR region code of the region where the request originates.
     * Field value example: `US`.
     * </pre>
     *
     * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearRegionCode() {
      
      regionCode_ = getDefaultInstance().getRegionCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required. CLDR region code of the region where the request originates.
     * Field value example: `US`.
     * </pre>
     *
     * <code>string region_code = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for regionCode to set.
     * @return This builder for chaining.
     */
    public Builder setRegionCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      regionCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sdkVersion_ = "";
    /**
     * <pre>
     * Version of the calling SDK, if applicable.
     * The version format is "major.minor.patch", example: `1.1.2`.
     * </pre>
     *
     * <code>string sdk_version = 3;</code>
     * @return The sdkVersion.
     */
    public java.lang.String getSdkVersion() {
      java.lang.Object ref = sdkVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdkVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version of the calling SDK, if applicable.
     * The version format is "major.minor.patch", example: `1.1.2`.
     * </pre>
     *
     * <code>string sdk_version = 3;</code>
     * @return The bytes for sdkVersion.
     */
    public com.google.protobuf.ByteString
        getSdkVersionBytes() {
      java.lang.Object ref = sdkVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdkVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version of the calling SDK, if applicable.
     * The version format is "major.minor.patch", example: `1.1.2`.
     * </pre>
     *
     * <code>string sdk_version = 3;</code>
     * @param value The sdkVersion to set.
     * @return This builder for chaining.
     */
    public Builder setSdkVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sdkVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the calling SDK, if applicable.
     * The version format is "major.minor.patch", example: `1.1.2`.
     * </pre>
     *
     * <code>string sdk_version = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSdkVersion() {
      
      sdkVersion_ = getDefaultInstance().getSdkVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the calling SDK, if applicable.
     * The version format is "major.minor.patch", example: `1.1.2`.
     * </pre>
     *
     * <code>string sdk_version = 3;</code>
     * @param value The bytes for sdkVersion to set.
     * @return This builder for chaining.
     */
    public Builder setSdkVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sdkVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object osVersion_ = "";
    /**
     * <pre>
     * Version of the operating system on which the calling SDK is running.
     * Field value examples: `4.4.1`, `12.1`.
     * </pre>
     *
     * <code>string os_version = 4;</code>
     * @return The osVersion.
     */
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version of the operating system on which the calling SDK is running.
     * Field value examples: `4.4.1`, `12.1`.
     * </pre>
     *
     * <code>string os_version = 4;</code>
     * @return The bytes for osVersion.
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version of the operating system on which the calling SDK is running.
     * Field value examples: `4.4.1`, `12.1`.
     * </pre>
     *
     * <code>string os_version = 4;</code>
     * @param value The osVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOsVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the operating system on which the calling SDK is running.
     * Field value examples: `4.4.1`, `12.1`.
     * </pre>
     *
     * <code>string os_version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsVersion() {
      
      osVersion_ = getDefaultInstance().getOsVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the operating system on which the calling SDK is running.
     * Field value examples: `4.4.1`, `12.1`.
     * </pre>
     *
     * <code>string os_version = 4;</code>
     * @param value The bytes for osVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOsVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceModel_ = "";
    /**
     * <pre>
     * Model of the device on which the calling SDK is running.
     * Field value examples: `iPhone12,1`, `SM-G920F`.
     * </pre>
     *
     * <code>string device_model = 5;</code>
     * @return The deviceModel.
     */
    public java.lang.String getDeviceModel() {
      java.lang.Object ref = deviceModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Model of the device on which the calling SDK is running.
     * Field value examples: `iPhone12,1`, `SM-G920F`.
     * </pre>
     *
     * <code>string device_model = 5;</code>
     * @return The bytes for deviceModel.
     */
    public com.google.protobuf.ByteString
        getDeviceModelBytes() {
      java.lang.Object ref = deviceModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Model of the device on which the calling SDK is running.
     * Field value examples: `iPhone12,1`, `SM-G920F`.
     * </pre>
     *
     * <code>string device_model = 5;</code>
     * @param value The deviceModel to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceModel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Model of the device on which the calling SDK is running.
     * Field value examples: `iPhone12,1`, `SM-G920F`.
     * </pre>
     *
     * <code>string device_model = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceModel() {
      
      deviceModel_ = getDefaultInstance().getDeviceModel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Model of the device on which the calling SDK is running.
     * Field value examples: `iPhone12,1`, `SM-G920F`.
     * </pre>
     *
     * <code>string device_model = 5;</code>
     * @param value The bytes for deviceModel to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceModel_ = value;
      onChanged();
      return this;
    }

    private int sdkType_ = 0;
    /**
     * <pre>
     * The type of SDK sending the request.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.SdkType sdk_type = 6;</code>
     * @return The enum numeric value on the wire for sdkType.
     */
    @java.lang.Override public int getSdkTypeValue() {
      return sdkType_;
    }
    /**
     * <pre>
     * The type of SDK sending the request.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.SdkType sdk_type = 6;</code>
     * @param value The enum numeric value on the wire for sdkType to set.
     * @return This builder for chaining.
     */
    public Builder setSdkTypeValue(int value) {
      
      sdkType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of SDK sending the request.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.SdkType sdk_type = 6;</code>
     * @return The sdkType.
     */
    @java.lang.Override
    public google.maps.fleetengine.v1.RequestHeader.SdkType getSdkType() {
      @SuppressWarnings("deprecation")
      google.maps.fleetengine.v1.RequestHeader.SdkType result = google.maps.fleetengine.v1.RequestHeader.SdkType.valueOf(sdkType_);
      return result == null ? google.maps.fleetengine.v1.RequestHeader.SdkType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The type of SDK sending the request.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.SdkType sdk_type = 6;</code>
     * @param value The sdkType to set.
     * @return This builder for chaining.
     */
    public Builder setSdkType(google.maps.fleetengine.v1.RequestHeader.SdkType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      sdkType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The type of SDK sending the request.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.SdkType sdk_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSdkType() {
      
      sdkType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object mapsSdkVersion_ = "";
    /**
     * <pre>
     * Version of the MapSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `5.2.1`.
     * </pre>
     *
     * <code>string maps_sdk_version = 7;</code>
     * @return The mapsSdkVersion.
     */
    public java.lang.String getMapsSdkVersion() {
      java.lang.Object ref = mapsSdkVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mapsSdkVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version of the MapSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `5.2.1`.
     * </pre>
     *
     * <code>string maps_sdk_version = 7;</code>
     * @return The bytes for mapsSdkVersion.
     */
    public com.google.protobuf.ByteString
        getMapsSdkVersionBytes() {
      java.lang.Object ref = mapsSdkVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mapsSdkVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version of the MapSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `5.2.1`.
     * </pre>
     *
     * <code>string maps_sdk_version = 7;</code>
     * @param value The mapsSdkVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMapsSdkVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mapsSdkVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the MapSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `5.2.1`.
     * </pre>
     *
     * <code>string maps_sdk_version = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapsSdkVersion() {
      
      mapsSdkVersion_ = getDefaultInstance().getMapsSdkVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the MapSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `5.2.1`.
     * </pre>
     *
     * <code>string maps_sdk_version = 7;</code>
     * @param value The bytes for mapsSdkVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMapsSdkVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mapsSdkVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object navSdkVersion_ = "";
    /**
     * <pre>
     * Version of the NavSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `2.1.0`.
     * </pre>
     *
     * <code>string nav_sdk_version = 8;</code>
     * @return The navSdkVersion.
     */
    public java.lang.String getNavSdkVersion() {
      java.lang.Object ref = navSdkVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        navSdkVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Version of the NavSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `2.1.0`.
     * </pre>
     *
     * <code>string nav_sdk_version = 8;</code>
     * @return The bytes for navSdkVersion.
     */
    public com.google.protobuf.ByteString
        getNavSdkVersionBytes() {
      java.lang.Object ref = navSdkVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        navSdkVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Version of the NavSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `2.1.0`.
     * </pre>
     *
     * <code>string nav_sdk_version = 8;</code>
     * @param value The navSdkVersion to set.
     * @return This builder for chaining.
     */
    public Builder setNavSdkVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      navSdkVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the NavSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `2.1.0`.
     * </pre>
     *
     * <code>string nav_sdk_version = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNavSdkVersion() {
      
      navSdkVersion_ = getDefaultInstance().getNavSdkVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of the NavSDK which the calling SDK depends on, if applicable.
     * The version format is "major.minor.patch", example: `2.1.0`.
     * </pre>
     *
     * <code>string nav_sdk_version = 8;</code>
     * @param value The bytes for navSdkVersion to set.
     * @return This builder for chaining.
     */
    public Builder setNavSdkVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      navSdkVersion_ = value;
      onChanged();
      return this;
    }

    private int platform_ = 0;
    /**
     * <pre>
     * Platform of the calling SDK.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.Platform platform = 9;</code>
     * @return The enum numeric value on the wire for platform.
     */
    @java.lang.Override public int getPlatformValue() {
      return platform_;
    }
    /**
     * <pre>
     * Platform of the calling SDK.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.Platform platform = 9;</code>
     * @param value The enum numeric value on the wire for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformValue(int value) {
      
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Platform of the calling SDK.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.Platform platform = 9;</code>
     * @return The platform.
     */
    @java.lang.Override
    public google.maps.fleetengine.v1.RequestHeader.Platform getPlatform() {
      @SuppressWarnings("deprecation")
      google.maps.fleetengine.v1.RequestHeader.Platform result = google.maps.fleetengine.v1.RequestHeader.Platform.valueOf(platform_);
      return result == null ? google.maps.fleetengine.v1.RequestHeader.Platform.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Platform of the calling SDK.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.Platform platform = 9;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(google.maps.fleetengine.v1.RequestHeader.Platform value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      platform_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Platform of the calling SDK.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader.Platform platform = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      
      platform_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object manufacturer_ = "";
    /**
     * <pre>
     * Manufacturer of the Android device from the calling SDK, only applicable
     * for the Android SDKs.
     * Field value example: `Samsung`.
     * </pre>
     *
     * <code>string manufacturer = 10;</code>
     * @return The manufacturer.
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Manufacturer of the Android device from the calling SDK, only applicable
     * for the Android SDKs.
     * Field value example: `Samsung`.
     * </pre>
     *
     * <code>string manufacturer = 10;</code>
     * @return The bytes for manufacturer.
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Manufacturer of the Android device from the calling SDK, only applicable
     * for the Android SDKs.
     * Field value example: `Samsung`.
     * </pre>
     *
     * <code>string manufacturer = 10;</code>
     * @param value The manufacturer to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      manufacturer_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Manufacturer of the Android device from the calling SDK, only applicable
     * for the Android SDKs.
     * Field value example: `Samsung`.
     * </pre>
     *
     * <code>string manufacturer = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearManufacturer() {
      
      manufacturer_ = getDefaultInstance().getManufacturer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Manufacturer of the Android device from the calling SDK, only applicable
     * for the Android SDKs.
     * Field value example: `Samsung`.
     * </pre>
     *
     * <code>string manufacturer = 10;</code>
     * @param value The bytes for manufacturer to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      manufacturer_ = value;
      onChanged();
      return this;
    }

    private int androidApiLevel_ ;
    /**
     * <pre>
     * Android API level of the calling SDK, only applicable for the Android SDKs.
     * Field value example: `23`.
     * </pre>
     *
     * <code>int32 android_api_level = 11;</code>
     * @return The androidApiLevel.
     */
    @java.lang.Override
    public int getAndroidApiLevel() {
      return androidApiLevel_;
    }
    /**
     * <pre>
     * Android API level of the calling SDK, only applicable for the Android SDKs.
     * Field value example: `23`.
     * </pre>
     *
     * <code>int32 android_api_level = 11;</code>
     * @param value The androidApiLevel to set.
     * @return This builder for chaining.
     */
    public Builder setAndroidApiLevel(int value) {
      
      androidApiLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Android API level of the calling SDK, only applicable for the Android SDKs.
     * Field value example: `23`.
     * </pre>
     *
     * <code>int32 android_api_level = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearAndroidApiLevel() {
      
      androidApiLevel_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.RequestHeader)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.RequestHeader)
  private static final google.maps.fleetengine.v1.RequestHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new google.maps.fleetengine.v1.RequestHeader();
  }

  public static google.maps.fleetengine.v1.RequestHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestHeader>
      PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
    @java.lang.Override
    public RequestHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.maps.fleetengine.v1.RequestHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

