// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicle_api.proto

package google.maps.fleetengine.v1;

public interface SearchVehiclesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.SearchVehiclesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of vehicles that match the `SearchVehiclesRequest` criteria, ordered
   * according to `SearchVehiclesRequest.order_by` field.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  java.util.List<google.maps.fleetengine.v1.VehicleMatch> 
      getMatchesList();
  /**
   * <pre>
   * List of vehicles that match the `SearchVehiclesRequest` criteria, ordered
   * according to `SearchVehiclesRequest.order_by` field.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  google.maps.fleetengine.v1.VehicleMatch getMatches(int index);
  /**
   * <pre>
   * List of vehicles that match the `SearchVehiclesRequest` criteria, ordered
   * according to `SearchVehiclesRequest.order_by` field.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  int getMatchesCount();
  /**
   * <pre>
   * List of vehicles that match the `SearchVehiclesRequest` criteria, ordered
   * according to `SearchVehiclesRequest.order_by` field.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  java.util.List<? extends google.maps.fleetengine.v1.VehicleMatchOrBuilder> 
      getMatchesOrBuilderList();
  /**
   * <pre>
   * List of vehicles that match the `SearchVehiclesRequest` criteria, ordered
   * according to `SearchVehiclesRequest.order_by` field.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  google.maps.fleetengine.v1.VehicleMatchOrBuilder getMatchesOrBuilder(
      int index);
}
