// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicle_api.proto

package google.maps.fleetengine.v1;

public interface SearchVehiclesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.SearchVehiclesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of vehicles that match the request options.
   * Ordered by ascending vehicle_pickup_eta, with ties broken by ascending
   * trip_type enum value, followed by matches that don't have
   * vehicle_pickup_eta set.
   * Example response: (Logically represented, not actual response fields):
   * * (VehicleId: Vehicle1, ETA: 10 AM, TripType: SHARED),
   * * (VehicleId: Vehicle2, ETA: 10 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle3, ETA: 11 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle4, ETA: Not set, TripType: SHARED),
   * * (VehicleId: Vehicle5, ETA: Not set, TripType: EXCLUSIVE)
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  java.util.List<google.maps.fleetengine.v1.VehicleMatch> 
      getMatchesList();
  /**
   * <pre>
   * List of vehicles that match the request options.
   * Ordered by ascending vehicle_pickup_eta, with ties broken by ascending
   * trip_type enum value, followed by matches that don't have
   * vehicle_pickup_eta set.
   * Example response: (Logically represented, not actual response fields):
   * * (VehicleId: Vehicle1, ETA: 10 AM, TripType: SHARED),
   * * (VehicleId: Vehicle2, ETA: 10 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle3, ETA: 11 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle4, ETA: Not set, TripType: SHARED),
   * * (VehicleId: Vehicle5, ETA: Not set, TripType: EXCLUSIVE)
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  google.maps.fleetengine.v1.VehicleMatch getMatches(int index);
  /**
   * <pre>
   * List of vehicles that match the request options.
   * Ordered by ascending vehicle_pickup_eta, with ties broken by ascending
   * trip_type enum value, followed by matches that don't have
   * vehicle_pickup_eta set.
   * Example response: (Logically represented, not actual response fields):
   * * (VehicleId: Vehicle1, ETA: 10 AM, TripType: SHARED),
   * * (VehicleId: Vehicle2, ETA: 10 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle3, ETA: 11 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle4, ETA: Not set, TripType: SHARED),
   * * (VehicleId: Vehicle5, ETA: Not set, TripType: EXCLUSIVE)
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  int getMatchesCount();
  /**
   * <pre>
   * List of vehicles that match the request options.
   * Ordered by ascending vehicle_pickup_eta, with ties broken by ascending
   * trip_type enum value, followed by matches that don't have
   * vehicle_pickup_eta set.
   * Example response: (Logically represented, not actual response fields):
   * * (VehicleId: Vehicle1, ETA: 10 AM, TripType: SHARED),
   * * (VehicleId: Vehicle2, ETA: 10 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle3, ETA: 11 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle4, ETA: Not set, TripType: SHARED),
   * * (VehicleId: Vehicle5, ETA: Not set, TripType: EXCLUSIVE)
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  java.util.List<? extends google.maps.fleetengine.v1.VehicleMatchOrBuilder> 
      getMatchesOrBuilderList();
  /**
   * <pre>
   * List of vehicles that match the request options.
   * Ordered by ascending vehicle_pickup_eta, with ties broken by ascending
   * trip_type enum value, followed by matches that don't have
   * vehicle_pickup_eta set.
   * Example response: (Logically represented, not actual response fields):
   * * (VehicleId: Vehicle1, ETA: 10 AM, TripType: SHARED),
   * * (VehicleId: Vehicle2, ETA: 10 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle3, ETA: 11 AM, TripType: EXCLUSIVE),
   * * (VehicleId: Vehicle4, ETA: Not set, TripType: SHARED),
   * * (VehicleId: Vehicle5, ETA: Not set, TripType: EXCLUSIVE)
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleMatch matches = 1;</code>
   */
  google.maps.fleetengine.v1.VehicleMatchOrBuilder getMatchesOrBuilder(
      int index);
}
