// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

public interface TerminalPointIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.TerminalPointId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return Whether the placeId field is set.
   */
  @java.lang.Deprecated boolean hasPlaceId();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return The placeId.
   */
  @java.lang.Deprecated java.lang.String getPlaceId();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string place_id = 2 [deprecated = true];</code>
   * @return The bytes for placeId.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getPlaceIdBytes();

  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return Whether the generatedId field is set.
   */
  @java.lang.Deprecated boolean hasGeneratedId();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return The generatedId.
   */
  @java.lang.Deprecated java.lang.String getGeneratedId();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>string generated_id = 3 [deprecated = true];</code>
   * @return The bytes for generatedId.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getGeneratedIdBytes();

  /**
   * <pre>
   * Unique ID of the terminal point.
   * </pre>
   *
   * <code>string value = 4;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * Unique ID of the terminal point.
   * </pre>
   *
   * <code>string value = 4;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  public google.maps.fleetengine.v1.TerminalPointId.IdCase getIdCase();
}
