// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/traffic.proto

package google.maps.fleetengine.v1;

public final class TrafficProto {
  private TrafficProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_SpeedReadingInterval_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_SpeedReadingInterval_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_ConsumableTrafficPolyline_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_ConsumableTrafficPolyline_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(google/maps/fleetengine/v1/traffic.pro" +
      "to\022\023maps.fleetengine.v1\"\343\001\n\024SpeedReading" +
      "Interval\022\"\n\032start_polyline_point_index\030\001" +
      " \001(\005\022 \n\030end_polyline_point_index\030\002 \001(\005\022>" +
      "\n\005speed\030\003 \001(\0162/.maps.fleetengine.v1.Spee" +
      "dReadingInterval.Speed\"E\n\005Speed\022\025\n\021SPEED" +
      "_UNSPECIFIED\020\000\022\n\n\006NORMAL\020\001\022\010\n\004SLOW\020\002\022\017\n\013" +
      "TRAFFIC_JAM\020\003\"\210\001\n\031ConsumableTrafficPolyl" +
      "ine\022I\n\026speed_reading_interval\030\001 \003(\0132).ma" +
      "ps.fleetengine.v1.SpeedReadingInterval\022 " +
      "\n\030encoded_path_to_waypoint\030\002 \001(\tBy\n\032goog" +
      "le.maps.fleetengine.v1B\014TrafficProtoP\001ZE" +
      "google.golang.org/genproto/googleapis/ma" +
      "ps/fleetengine/v1;fleetengine\242\002\003CFEb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_maps_fleetengine_v1_SpeedReadingInterval_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maps_fleetengine_v1_SpeedReadingInterval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_SpeedReadingInterval_descriptor,
        new java.lang.String[] { "StartPolylinePointIndex", "EndPolylinePointIndex", "Speed", });
    internal_static_maps_fleetengine_v1_ConsumableTrafficPolyline_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maps_fleetengine_v1_ConsumableTrafficPolyline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_ConsumableTrafficPolyline_descriptor,
        new java.lang.String[] { "SpeedReadingInterval", "EncodedPathToWaypoint", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
