// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicle_api.proto

package google.maps.fleetengine.v1;

public interface UpdateVehicleAttributesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.UpdateVehicleAttributesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The updated full list of vehicle attributes, including new,
   * altered and untouched attributes.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  java.util.List<google.maps.fleetengine.v1.VehicleAttribute> 
      getAttributesList();
  /**
   * <pre>
   * Required. The updated full list of vehicle attributes, including new,
   * altered and untouched attributes.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  google.maps.fleetengine.v1.VehicleAttribute getAttributes(int index);
  /**
   * <pre>
   * Required. The updated full list of vehicle attributes, including new,
   * altered and untouched attributes.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  int getAttributesCount();
  /**
   * <pre>
   * Required. The updated full list of vehicle attributes, including new,
   * altered and untouched attributes.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  java.util.List<? extends google.maps.fleetengine.v1.VehicleAttributeOrBuilder> 
      getAttributesOrBuilderList();
  /**
   * <pre>
   * Required. The updated full list of vehicle attributes, including new,
   * altered and untouched attributes.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  google.maps.fleetengine.v1.VehicleAttributeOrBuilder getAttributesOrBuilder(
      int index);
}
