// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicle_api.proto

package google.maps.fleetengine.v1;

public interface UpdateVehicleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.UpdateVehicleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   * @return The header.
   */
  google.maps.fleetengine.v1.RequestHeader getHeader();
  /**
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   */
  google.maps.fleetengine.v1.RequestHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * Required. Must be in the format
   * `providers/{provider}/vehicles/{vehicle}`.
   * The {provider} must be the Project ID (for example, `sample-cloud-project`)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * </pre>
   *
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. Must be in the format
   * `providers/{provider}/vehicles/{vehicle}`.
   * The {provider} must be the Project ID (for example, `sample-cloud-project`)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * </pre>
   *
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Required. The `Vehicle` entity values to apply.  When updating a `Vehicle`,
   * the following fields may not be updated as they are managed by the
   * server.
   * * `current_trips`
   * * `available_capacity`
   * * `current_route_segment_version`
   * * `waypoints_version`
   * Furthermore, the vehicle `name` cannot be updated.
   * If the `attributes` field is updated, **all** the vehicle's attributes are
   * replaced with the attributes provided in the request. If you want to update
   * only some attributes, see the `UpdateVehicleAttributes` method. Likewise,
   * the `waypoints` field can be updated, but must contain all the waypoints.
   * currently on the vehicle, and no other waypoints.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the vehicle field is set.
   */
  boolean hasVehicle();
  /**
   * <pre>
   * Required. The `Vehicle` entity values to apply.  When updating a `Vehicle`,
   * the following fields may not be updated as they are managed by the
   * server.
   * * `current_trips`
   * * `available_capacity`
   * * `current_route_segment_version`
   * * `waypoints_version`
   * Furthermore, the vehicle `name` cannot be updated.
   * If the `attributes` field is updated, **all** the vehicle's attributes are
   * replaced with the attributes provided in the request. If you want to update
   * only some attributes, see the `UpdateVehicleAttributes` method. Likewise,
   * the `waypoints` field can be updated, but must contain all the waypoints.
   * currently on the vehicle, and no other waypoints.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The vehicle.
   */
  google.maps.fleetengine.v1.Vehicle getVehicle();
  /**
   * <pre>
   * Required. The `Vehicle` entity values to apply.  When updating a `Vehicle`,
   * the following fields may not be updated as they are managed by the
   * server.
   * * `current_trips`
   * * `available_capacity`
   * * `current_route_segment_version`
   * * `waypoints_version`
   * Furthermore, the vehicle `name` cannot be updated.
   * If the `attributes` field is updated, **all** the vehicle's attributes are
   * replaced with the attributes provided in the request. If you want to update
   * only some attributes, see the `UpdateVehicleAttributes` method. Likewise,
   * the `waypoints` field can be updated, but must contain all the waypoints.
   * currently on the vehicle, and no other waypoints.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.Vehicle vehicle = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  google.maps.fleetengine.v1.VehicleOrBuilder getVehicleOrBuilder();

  /**
   * <pre>
   * Required. A field mask indicating which fields of the `Vehicle` to update.
   * At least one field name must be provided.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * Required. A field mask indicating which fields of the `Vehicle` to update.
   * At least one field name must be provided.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * Required. A field mask indicating which fields of the `Vehicle` to update.
   * At least one field name must be provided.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
