// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/fleetengine.proto

package google.maps.fleetengine.v1;

public interface VehicleAttributeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.VehicleAttribute)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The attribute's key. Keys may not contain the colon character (:).
   * </pre>
   *
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <pre>
   * The attribute's key. Keys may not contain the colon character (:).
   * </pre>
   *
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   * The attribute's value.
   * </pre>
   *
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * The attribute's value.
   * </pre>
   *
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
