// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicles.proto

package google.maps.fleetengine.v1;

public final class Vehicles {
  private Vehicles() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_Vehicle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_Vehicle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_Vehicle_VehicleType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_Vehicle_VehicleType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_BatteryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_BatteryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_DeviceSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_DeviceSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_LicensePlate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_LicensePlate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_RoadStretch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_RoadStretch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maps_fleetengine_v1_TrafficPolylineData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_TrafficPolylineData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)google/maps/fleetengine/v1/vehicles.pr" +
      "oto\022\023maps.fleetengine.v1\032\037google/api/fie" +
      "ld_behavior.proto\032\031google/api/resource.p" +
      "roto\032,google/maps/fleetengine/v1/fleeten" +
      "gine.proto\032\037google/protobuf/timestamp.pr" +
      "oto\032\036google/protobuf/wrappers.proto\"\300\013\n\007" +
      "Vehicle\022\021\n\004name\030\001 \001(\tB\003\340A\003\0228\n\rvehicle_st" +
      "ate\030\002 \001(\0162!.maps.fleetengine.v1.VehicleS" +
      "tate\022;\n\024supported_trip_types\030\003 \003(\0162\035.map" +
      "s.fleetengine.v1.TripType\022\032\n\rcurrent_tri" +
      "ps\030\004 \003(\tB\003\340A\003\022;\n\rlast_location\030\005 \001(\0132$.m" +
      "aps.fleetengine.v1.VehicleLocation\022\030\n\020ma" +
      "ximum_capacity\030\006 \001(\005\0229\n\nattributes\030\010 \003(\013" +
      "2%.maps.fleetengine.v1.VehicleAttribute\022" +
      ">\n\014vehicle_type\030\t \001(\0132(.maps.fleetengine" +
      ".v1.Vehicle.VehicleType\0228\n\rlicense_plate" +
      "\030\n \001(\0132!.maps.fleetengine.v1.LicensePlat" +
      "e\0228\n\005route\030\014 \003(\0132%.maps.fleetengine.v1.T" +
      "erminalLocationB\002\030\001\022\035\n\025current_route_seg" +
      "ment\030\024 \001(\t\022T\n\035current_route_segment_traf" +
      "fic\030\034 \001(\0132(.maps.fleetengine.v1.TrafficP" +
      "olylineDataB\003\340A\004\022F\n\035current_route_segmen" +
      "t_version\030\017 \001(\0132\032.google.protobuf.Timest" +
      "ampB\003\340A\003\022J\n\037current_route_segment_end_po" +
      "int\030\030 \001(\0132!.maps.fleetengine.v1.TripWayp" +
      "oint\022>\n\031remaining_distance_meters\030\022 \001(\0132" +
      "\033.google.protobuf.Int32Value\0229\n\025eta_to_f" +
      "irst_waypoint\030\023 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\022@\n\026remaining_time_seconds\030\031 \001(\0132" +
      "\033.google.protobuf.Int32ValueB\003\340A\004\0224\n\tway" +
      "points\030\026 \003(\0132!.maps.fleetengine.v1.TripW" +
      "aypoint\022:\n\021waypoints_version\030\020 \001(\0132\032.goo" +
      "gle.protobuf.TimestampB\003\340A\003\022\034\n\024back_to_b" +
      "ack_enabled\030\027 \001(\010\022@\n\021navigation_status\030\032" +
      " \001(\0162%.maps.fleetengine.v1.NavigationSta" +
      "tus\022A\n\017device_settings\030\033 \001(\0132#.maps.flee" +
      "tengine.v1.DeviceSettingsB\003\340A\004\032\233\001\n\013Vehic" +
      "leType\022C\n\010category\030\001 \001(\01621.maps.fleeteng" +
      "ine.v1.Vehicle.VehicleType.Category\"G\n\010C" +
      "ategory\022\013\n\007UNKNOWN\020\000\022\010\n\004AUTO\020\001\022\010\n\004TAXI\020\002" +
      "\022\t\n\005TRUCK\020\003\022\017\n\013TWO_WHEELER\020\004:P\352AM\n\"fleet" +
      "engine.googleapis.com/Vehicle\022\'providers" +
      "/{provider}/vehicles/{vehicle}\"\235\001\n\013Batte" +
      "ryInfo\022:\n\016battery_status\030\001 \001(\0162\".maps.fl" +
      "eetengine.v1.BatteryStatus\0226\n\014power_sour" +
      "ce\030\002 \001(\0162 .maps.fleetengine.v1.PowerSour" +
      "ce\022\032\n\022battery_percentage\030\003 \001(\002\"\312\001\n\016Devic" +
      "eSettings\022L\n\030location_power_save_mode\030\001 " +
      "\001(\0162*.maps.fleetengine.v1.LocationPowerS" +
      "aveMode\022\032\n\022is_power_save_mode\030\002 \001(\010\022\026\n\016i" +
      "s_interactive\030\003 \001(\010\0226\n\014battery_info\030\004 \001(" +
      "\0132 .maps.fleetengine.v1.BatteryInfo\"A\n\014L" +
      "icensePlate\022\031\n\014country_code\030\001 \001(\tB\003\340A\002\022\026" +
      "\n\016last_character\030\002 \001(\t\"\366\002\n$VisualTraffic" +
      "ReportPolylineRendering\022`\n\014road_stretch\030" +
      "\001 \003(\0132E.maps.fleetengine.v1.VisualTraffi" +
      "cReportPolylineRendering.RoadStretchB\003\340A" +
      "\001\032\353\001\n\013RoadStretch\022_\n\005style\030\001 \001(\0162K.maps." +
      "fleetengine.v1.VisualTrafficReportPolyli" +
      "neRendering.RoadStretch.StyleB\003\340A\002\022\032\n\rof" +
      "fset_meters\030\002 \001(\005B\003\340A\002\022\032\n\rlength_meters\030" +
      "\003 \001(\005B\003\340A\002\"C\n\005Style\022\025\n\021STYLE_UNSPECIFIED" +
      "\020\000\022\022\n\016SLOWER_TRAFFIC\020\001\022\017\n\013TRAFFIC_JAM\020\002\"" +
      "k\n\023TrafficPolylineData\022T\n\021traffic_render" +
      "ing\030\001 \001(\01329.maps.fleetengine.v1.VisualTr" +
      "afficReportPolylineRendering*B\n\014VehicleS" +
      "tate\022\031\n\025UNKNOWN_VEHICLE_STATE\020\000\022\013\n\007OFFLI" +
      "NE\020\001\022\n\n\006ONLINE\020\002*\222\002\n\025LocationPowerSaveMo" +
      "de\022$\n UNKNOWN_LOCATION_POWER_SAVE_MODE\020\000" +
      "\022\033\n\027LOCATION_MODE_NO_CHANGE\020\001\022.\n*LOCATIO" +
      "N_MODE_GPS_DISABLED_WHEN_SCREEN_OFF\020\002\022.\n" +
      "*LOCATION_MODE_ALL_DISABLED_WHEN_SCREEN_" +
      "OFF\020\003\022!\n\035LOCATION_MODE_FOREGROUND_ONLY\020\004" +
      "\0223\n/LOCATION_MODE_THROTTLE_REQUESTS_WHEN" +
      "_SCREEN_OFF\020\005*\300\001\n\rBatteryStatus\022\032\n\026UNKNO" +
      "WN_BATTERY_STATUS\020\000\022\033\n\027BATTERY_STATUS_CH" +
      "ARGING\020\001\022\036\n\032BATTERY_STATUS_DISCHARGING\020\002" +
      "\022\027\n\023BATTERY_STATUS_FULL\020\003\022\037\n\033BATTERY_STA" +
      "TUS_NOT_CHARGING\020\004\022\034\n\030BATTERY_STATUS_POW" +
      "ER_LOW\020\005*\211\001\n\013PowerSource\022\030\n\024UNKNOWN_POWE" +
      "R_SOURCE\020\000\022\023\n\017POWER_SOURCE_AC\020\001\022\024\n\020POWER" +
      "_SOURCE_USB\020\002\022\031\n\025POWER_SOURCE_WIRELESS\020\003" +
      "\022\032\n\026POWER_SOURCE_UNPLUGGED\020\004Bu\n\032google.m" +
      "aps.fleetengine.v1B\010VehiclesP\001ZEgoogle.g" +
      "olang.org/genproto/googleapis/maps/fleet" +
      "engine/v1;fleetengine\242\002\003CFEb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          google.maps.fleetengine.v1.FleetEngine.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_maps_fleetengine_v1_Vehicle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maps_fleetengine_v1_Vehicle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_Vehicle_descriptor,
        new java.lang.String[] { "Name", "VehicleState", "SupportedTripTypes", "CurrentTrips", "LastLocation", "MaximumCapacity", "Attributes", "VehicleType", "LicensePlate", "Route", "CurrentRouteSegment", "CurrentRouteSegmentTraffic", "CurrentRouteSegmentVersion", "CurrentRouteSegmentEndPoint", "RemainingDistanceMeters", "EtaToFirstWaypoint", "RemainingTimeSeconds", "Waypoints", "WaypointsVersion", "BackToBackEnabled", "NavigationStatus", "DeviceSettings", });
    internal_static_maps_fleetengine_v1_Vehicle_VehicleType_descriptor =
      internal_static_maps_fleetengine_v1_Vehicle_descriptor.getNestedTypes().get(0);
    internal_static_maps_fleetengine_v1_Vehicle_VehicleType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_Vehicle_VehicleType_descriptor,
        new java.lang.String[] { "Category", });
    internal_static_maps_fleetengine_v1_BatteryInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maps_fleetengine_v1_BatteryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_BatteryInfo_descriptor,
        new java.lang.String[] { "BatteryStatus", "PowerSource", "BatteryPercentage", });
    internal_static_maps_fleetengine_v1_DeviceSettings_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_maps_fleetengine_v1_DeviceSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_DeviceSettings_descriptor,
        new java.lang.String[] { "LocationPowerSaveMode", "IsPowerSaveMode", "IsInteractive", "BatteryInfo", });
    internal_static_maps_fleetengine_v1_LicensePlate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_maps_fleetengine_v1_LicensePlate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_LicensePlate_descriptor,
        new java.lang.String[] { "CountryCode", "LastCharacter", });
    internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_descriptor,
        new java.lang.String[] { "RoadStretch", });
    internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_RoadStretch_descriptor =
      internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_descriptor.getNestedTypes().get(0);
    internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_RoadStretch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_VisualTrafficReportPolylineRendering_RoadStretch_descriptor,
        new java.lang.String[] { "Style", "OffsetMeters", "LengthMeters", });
    internal_static_maps_fleetengine_v1_TrafficPolylineData_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_maps_fleetengine_v1_TrafficPolylineData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maps_fleetengine_v1_TrafficPolylineData_descriptor,
        new java.lang.String[] { "TrafficRendering", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    google.maps.fleetengine.v1.FleetEngine.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
