// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicle_api.proto

package google.maps.fleetengine.v1;

public interface VehicleAttributeListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.VehicleAttributeList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of attributes in this collection.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1;</code>
   */
  java.util.List<google.maps.fleetengine.v1.VehicleAttribute> 
      getAttributesList();
  /**
   * <pre>
   * A list of attributes in this collection.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1;</code>
   */
  google.maps.fleetengine.v1.VehicleAttribute getAttributes(int index);
  /**
   * <pre>
   * A list of attributes in this collection.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1;</code>
   */
  int getAttributesCount();
  /**
   * <pre>
   * A list of attributes in this collection.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1;</code>
   */
  java.util.List<? extends google.maps.fleetengine.v1.VehicleAttributeOrBuilder> 
      getAttributesOrBuilderList();
  /**
   * <pre>
   * A list of attributes in this collection.
   * </pre>
   *
   * <code>repeated .maps.fleetengine.v1.VehicleAttribute attributes = 1;</code>
   */
  google.maps.fleetengine.v1.VehicleAttributeOrBuilder getAttributesOrBuilder(
      int index);
}
