// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicle_api.proto

package google.maps.fleetengine.v1;

public interface WaypointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maps.fleetengine.v1.Waypoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The location of this waypoint.
   * </pre>
   *
   * <code>.google.type.LatLng lat_lng = 1;</code>
   * @return Whether the latLng field is set.
   */
  boolean hasLatLng();
  /**
   * <pre>
   * The location of this waypoint.
   * </pre>
   *
   * <code>.google.type.LatLng lat_lng = 1;</code>
   * @return The latLng.
   */
  com.google.type.LatLng getLatLng();
  /**
   * <pre>
   * The location of this waypoint.
   * </pre>
   *
   * <code>.google.type.LatLng lat_lng = 1;</code>
   */
  com.google.type.LatLngOrBuilder getLatLngOrBuilder();

  /**
   * <pre>
   * The estimated time that the vehicle will arrive at this waypoint.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp eta = 2;</code>
   * @return Whether the eta field is set.
   */
  boolean hasEta();
  /**
   * <pre>
   * The estimated time that the vehicle will arrive at this waypoint.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp eta = 2;</code>
   * @return The eta.
   */
  com.google.protobuf.Timestamp getEta();
  /**
   * <pre>
   * The estimated time that the vehicle will arrive at this waypoint.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp eta = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEtaOrBuilder();
}
