// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protos from '../protos/protos';
import * as assert from 'assert';
import * as sinon from 'sinon';
import {SinonStub} from 'sinon';
import { describe, it } from 'mocha';
import * as tripserviceModule from '../src';

import {PassThrough} from 'stream';

import {protobuf} from 'google-gax';

function generateSampleMessage<T extends object>(instance: T) {
    const filledObject = (instance.constructor as typeof protobuf.Message)
        .toObject(instance as protobuf.Message<T>, {defaults: true});
    return (instance.constructor as typeof protobuf.Message).fromObject(filledObject) as T;
}

function stubSimpleCall<ResponseType>(response?: ResponseType, error?: Error) {
    return error ? sinon.stub().rejects(error) : sinon.stub().resolves([response]);
}

function stubSimpleCallWithCallback<ResponseType>(response?: ResponseType, error?: Error) {
    return error ? sinon.stub().callsArgWith(2, error) : sinon.stub().callsArgWith(2, null, response);
}

function stubPageStreamingCall<ResponseType>(responses?: ResponseType[], error?: Error) {
    const pagingStub = sinon.stub();
    if (responses) {
        for (let i = 0; i < responses.length; ++i) {
            pagingStub.onCall(i).callsArgWith(2, null, responses[i]);
        }
    }
    const transformStub = error ? sinon.stub().callsArgWith(2, error) : pagingStub;
    const mockStream = new PassThrough({
        objectMode: true,
        transform: transformStub,
    });
    // trigger as many responses as needed
    if (responses) {
        for (let i = 0; i < responses.length; ++i) {
            setImmediate(() => { mockStream.write({}); });
        }
        setImmediate(() => { mockStream.end(); });
    } else {
        setImmediate(() => { mockStream.write({}); });
        setImmediate(() => { mockStream.end(); });
    }
    return sinon.stub().returns(mockStream);
}

function stubAsyncIterationCall<ResponseType>(responses?: ResponseType[], error?: Error) {
    let counter = 0;
    const asyncIterable = {
        [Symbol.asyncIterator]() {
            return {
                async next() {
                    if (error) {
                        return Promise.reject(error);
                    }
                    if (counter >= responses!.length) {
                        return Promise.resolve({done: true, value: undefined});
                    }
                    return Promise.resolve({done: false, value: responses![counter++]});
                }
            };
        }
    };
    return sinon.stub().returns(asyncIterable);
}

describe('v1.TripServiceClient', () => {
    it('has servicePath', () => {
        const servicePath = tripserviceModule.v1.TripServiceClient.servicePath;
        assert(servicePath);
    });

    it('has apiEndpoint', () => {
        const apiEndpoint = tripserviceModule.v1.TripServiceClient.apiEndpoint;
        assert(apiEndpoint);
    });

    it('has port', () => {
        const port = tripserviceModule.v1.TripServiceClient.port;
        assert(port);
        assert(typeof port === 'number');
    });

    it('should create a client with no option', () => {
        const client = new tripserviceModule.v1.TripServiceClient();
        assert(client);
    });

    it('should create a client with gRPC fallback', () => {
        const client = new tripserviceModule.v1.TripServiceClient({
            fallback: true,
        });
        assert(client);
    });

    it('has initialize method and supports deferred initialization', async () => {
        const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
        assert.strictEqual(client.tripServiceStub, undefined);
        await client.initialize();
        assert(client.tripServiceStub);
    });

    it('has close method', () => {
        const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
        client.close();
    });

    it('has getProjectId method', async () => {
        const fakeProjectId = 'fake-project-id';
        const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
        client.auth.getProjectId = sinon.stub().resolves(fakeProjectId);
        const result = await client.getProjectId();
        assert.strictEqual(result, fakeProjectId);
        assert((client.auth.getProjectId as SinonStub).calledWithExactly());
    });

    it('has getProjectId method with callback', async () => {
        const fakeProjectId = 'fake-project-id';
        const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
        client.auth.getProjectId = sinon.stub().callsArgWith(0, null, fakeProjectId);
        const promise = new Promise((resolve, reject) => {
            client.getProjectId((err?: Error|null, projectId?: string|null) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(projectId);
                }
            });
        });
        const result = await promise;
        assert.strictEqual(result, fakeProjectId);
    });

    describe('createTrip', () => {
        it('invokes createTrip without error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.CreateTripRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.maps.fleetengine.v1.Trip());
            client.innerApiCalls.createTrip = stubSimpleCall(expectedResponse);
            const [response] = await client.createTrip(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.createTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes createTrip without error using callback', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.CreateTripRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.maps.fleetengine.v1.Trip());
            client.innerApiCalls.createTrip = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.createTrip(
                    request,
                    (err?: Error|null, result?: protos.maps.fleetengine.v1.ITrip|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.createTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes createTrip with error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.CreateTripRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.createTrip = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.createTrip(request), expectedError);
            assert((client.innerApiCalls.createTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('getTrip', () => {
        it('invokes getTrip without error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.GetTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.maps.fleetengine.v1.Trip());
            client.innerApiCalls.getTrip = stubSimpleCall(expectedResponse);
            const [response] = await client.getTrip(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes getTrip without error using callback', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.GetTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.maps.fleetengine.v1.Trip());
            client.innerApiCalls.getTrip = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.getTrip(
                    request,
                    (err?: Error|null, result?: protos.maps.fleetengine.v1.ITrip|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.getTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes getTrip with error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.GetTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.getTrip = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.getTrip(request), expectedError);
            assert((client.innerApiCalls.getTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('reportBillableTrip', () => {
        it('invokes reportBillableTrip without error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.ReportBillableTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.protobuf.Empty());
            client.innerApiCalls.reportBillableTrip = stubSimpleCall(expectedResponse);
            const [response] = await client.reportBillableTrip(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.reportBillableTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes reportBillableTrip without error using callback', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.ReportBillableTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.google.protobuf.Empty());
            client.innerApiCalls.reportBillableTrip = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.reportBillableTrip(
                    request,
                    (err?: Error|null, result?: protos.google.protobuf.IEmpty|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.reportBillableTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes reportBillableTrip with error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.ReportBillableTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.reportBillableTrip = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.reportBillableTrip(request), expectedError);
            assert((client.innerApiCalls.reportBillableTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('updateTrip', () => {
        it('invokes updateTrip without error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.UpdateTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.maps.fleetengine.v1.Trip());
            client.innerApiCalls.updateTrip = stubSimpleCall(expectedResponse);
            const [response] = await client.updateTrip(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.updateTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes updateTrip without error using callback', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.UpdateTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = generateSampleMessage(new protos.maps.fleetengine.v1.Trip());
            client.innerApiCalls.updateTrip = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.updateTrip(
                    request,
                    (err?: Error|null, result?: protos.maps.fleetengine.v1.ITrip|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.updateTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes updateTrip with error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.UpdateTripRequest());
            request.name = '';
            const expectedHeaderRequestParams = "name=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.updateTrip = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.updateTrip(request), expectedError);
            assert((client.innerApiCalls.updateTrip as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });
    });

    describe('searchTrips', () => {
        it('invokes searchTrips without error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.SearchTripsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = [
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
            ];
            client.innerApiCalls.searchTrips = stubSimpleCall(expectedResponse);
            const [response] = await client.searchTrips(request);
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.searchTrips as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes searchTrips without error using callback', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.SearchTripsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedResponse = [
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
            ];
            client.innerApiCalls.searchTrips = stubSimpleCallWithCallback(expectedResponse);
            const promise = new Promise((resolve, reject) => {
                 client.searchTrips(
                    request,
                    (err?: Error|null, result?: protos.maps.fleetengine.v1.ITrip[]|null) => {
                        if (err) {
                            reject(err);
                        } else {
                            resolve(result);
                        }
                    });
            });
            const response = await promise;
            assert.deepStrictEqual(response, expectedResponse);
            assert((client.innerApiCalls.searchTrips as SinonStub)
                .getCall(0).calledWith(request, expectedOptions /*, callback defined above */));
        });

        it('invokes searchTrips with error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.SearchTripsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedOptions = {
                otherArgs: {
                    headers: {
                        'x-goog-request-params': expectedHeaderRequestParams,
                    },
                },
            };
            const expectedError = new Error('expected');
            client.innerApiCalls.searchTrips = stubSimpleCall(undefined, expectedError);
            await assert.rejects(client.searchTrips(request), expectedError);
            assert((client.innerApiCalls.searchTrips as SinonStub)
                .getCall(0).calledWith(request, expectedOptions, undefined));
        });

        it('invokes searchTripsStream without error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.SearchTripsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedResponse = [
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
            ];
            client.descriptors.page.searchTrips.createStream = stubPageStreamingCall(expectedResponse);
            const stream = client.searchTripsStream(request);
            const promise = new Promise((resolve, reject) => {
                const responses: protos.maps.fleetengine.v1.Trip[] = [];
                stream.on('data', (response: protos.maps.fleetengine.v1.Trip) => {
                    responses.push(response);
                });
                stream.on('end', () => {
                    resolve(responses);
                });
                stream.on('error', (err: Error) => {
                    reject(err);
                });
            });
            const responses = await promise;
            assert.deepStrictEqual(responses, expectedResponse);
            assert((client.descriptors.page.searchTrips.createStream as SinonStub)
                .getCall(0).calledWith(client.innerApiCalls.searchTrips, request));
            assert.strictEqual(
                (client.descriptors.page.searchTrips.createStream as SinonStub)
                    .getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
                expectedHeaderRequestParams
            );
        });

        it('invokes searchTripsStream with error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.SearchTripsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedError = new Error('expected');
            client.descriptors.page.searchTrips.createStream = stubPageStreamingCall(undefined, expectedError);
            const stream = client.searchTripsStream(request);
            const promise = new Promise((resolve, reject) => {
                const responses: protos.maps.fleetengine.v1.Trip[] = [];
                stream.on('data', (response: protos.maps.fleetengine.v1.Trip) => {
                    responses.push(response);
                });
                stream.on('end', () => {
                    resolve(responses);
                });
                stream.on('error', (err: Error) => {
                    reject(err);
                });
            });
            await assert.rejects(promise, expectedError);
            assert((client.descriptors.page.searchTrips.createStream as SinonStub)
                .getCall(0).calledWith(client.innerApiCalls.searchTrips, request));
            assert.strictEqual(
                (client.descriptors.page.searchTrips.createStream as SinonStub)
                    .getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
                expectedHeaderRequestParams
            );
        });

        it('uses async iteration with searchTrips without error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
              credentials: {client_email: 'bogus', private_key: 'bogus'},
              projectId: 'bogus',
        });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.SearchTripsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";
            const expectedResponse = [
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
              generateSampleMessage(new protos.maps.fleetengine.v1.Trip()),
            ];
            client.descriptors.page.searchTrips.asyncIterate = stubAsyncIterationCall(expectedResponse);
            const responses: protos.maps.fleetengine.v1.ITrip[] = [];
            const iterable = client.searchTripsAsync(request);
            for await (const resource of iterable) {
                responses.push(resource!);
            }
            assert.deepStrictEqual(responses, expectedResponse);
            assert.deepStrictEqual(
                (client.descriptors.page.searchTrips.asyncIterate as SinonStub)
                    .getCall(0).args[1], request);
            assert.strictEqual(
                (client.descriptors.page.searchTrips.asyncIterate as SinonStub)
                    .getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
                expectedHeaderRequestParams
            );
        });

        it('uses async iteration with searchTrips with error', async () => {
            const client = new tripserviceModule.v1.TripServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            const request = generateSampleMessage(new protos.maps.fleetengine.v1.SearchTripsRequest());
            request.parent = '';
            const expectedHeaderRequestParams = "parent=";const expectedError = new Error('expected');
            client.descriptors.page.searchTrips.asyncIterate = stubAsyncIterationCall(undefined, expectedError);
            const iterable = client.searchTripsAsync(request);
            await assert.rejects(async () => {
                const responses: protos.maps.fleetengine.v1.ITrip[] = [];
                for await (const resource of iterable) {
                    responses.push(resource!);
                }
            });
            assert.deepStrictEqual(
                (client.descriptors.page.searchTrips.asyncIterate as SinonStub)
                    .getCall(0).args[1], request);
            assert.strictEqual(
                (client.descriptors.page.searchTrips.asyncIterate as SinonStub)
                    .getCall(0).args[2].otherArgs.headers['x-goog-request-params'],
                expectedHeaderRequestParams
            );
        });
    });

    describe('Path templates', () => {

        describe('trip', () => {
            const fakePath = "/rendered/path/trip";
            const expectedParameters = {
                provider: "providerValue",
                trip: "tripValue",
            };
            const client = new tripserviceModule.v1.TripServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            client.pathTemplates.tripPathTemplate.render =
                sinon.stub().returns(fakePath);
            client.pathTemplates.tripPathTemplate.match =
                sinon.stub().returns(expectedParameters);

            it('tripPath', () => {
                const result = client.tripPath("providerValue", "tripValue");
                assert.strictEqual(result, fakePath);
                assert((client.pathTemplates.tripPathTemplate.render as SinonStub)
                    .getCall(-1).calledWith(expectedParameters));
            });

            it('matchProviderFromTripName', () => {
                const result = client.matchProviderFromTripName(fakePath);
                assert.strictEqual(result, "providerValue");
                assert((client.pathTemplates.tripPathTemplate.match as SinonStub)
                    .getCall(-1).calledWith(fakePath));
            });

            it('matchTripFromTripName', () => {
                const result = client.matchTripFromTripName(fakePath);
                assert.strictEqual(result, "tripValue");
                assert((client.pathTemplates.tripPathTemplate.match as SinonStub)
                    .getCall(-1).calledWith(fakePath));
            });
        });

        describe('vehicle', () => {
            const fakePath = "/rendered/path/vehicle";
            const expectedParameters = {
                provider: "providerValue",
                vehicle: "vehicleValue",
            };
            const client = new tripserviceModule.v1.TripServiceClient({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            client.initialize();
            client.pathTemplates.vehiclePathTemplate.render =
                sinon.stub().returns(fakePath);
            client.pathTemplates.vehiclePathTemplate.match =
                sinon.stub().returns(expectedParameters);

            it('vehiclePath', () => {
                const result = client.vehiclePath("providerValue", "vehicleValue");
                assert.strictEqual(result, fakePath);
                assert((client.pathTemplates.vehiclePathTemplate.render as SinonStub)
                    .getCall(-1).calledWith(expectedParameters));
            });

            it('matchProviderFromVehicleName', () => {
                const result = client.matchProviderFromVehicleName(fakePath);
                assert.strictEqual(result, "providerValue");
                assert((client.pathTemplates.vehiclePathTemplate.match as SinonStub)
                    .getCall(-1).calledWith(fakePath));
            });

            it('matchVehicleFromVehicleName', () => {
                const result = client.matchVehicleFromVehicleName(fakePath);
                assert.strictEqual(result, "vehicleValue");
                assert((client.pathTemplates.vehiclePathTemplate.match as SinonStub)
                    .getCall(-1).calledWith(fakePath));
            });
        });
    });
});
