// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/vehicles.proto

package google.maps.fleetengine.v1;

public final class Vehicles {
  private Vehicles() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_maps_fleetengine_v1_Vehicle_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_Vehicle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_maps_fleetengine_v1_Vehicle_VehicleType_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_Vehicle_VehicleType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_maps_fleetengine_v1_BatteryInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_BatteryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_maps_fleetengine_v1_DeviceSettings_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_DeviceSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_maps_fleetengine_v1_LicensePlate_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maps_fleetengine_v1_LicensePlate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + ")google/maps/fleetengine/v1/vehicles.proto\022\023maps.fleetengine.v1\032\037google/api/field_behavior.proto\032\031google/api/resource.proto\032,google/maps/fleetengine/v1/fleetengine.proto\032\037google/protobuf/timestamp.proto\032\036google/protobuf/wrappers.proto\"\350\n\n"
          + "\007Vehicle\022\014\n"
          + "\004name\030\001 \001(\t\0228\n\r"
          + "vehicle_state\030\002 \001(\0162!.maps.fleetengine.v1.VehicleState\022;\n"
          + "\024supported_trip_types\030\003"
          + " \003(\0162\035.maps.fleetengine.v1.TripType\022\025\n\r"
          + "current_trips\030\004 \003(\t\022;\n\r"
          + "last_location\030\005 \001(\0132$.maps.fleetengine.v1.VehicleLocation\022\030\n"
          + "\020maximum_capacity\030\006 \001(\005\022\032\n"
          + "\022available_capacity\030\007 \001(\005\0229\n\n"
          + "attributes\030\010 \003(\0132%.maps.fleetengine.v1.VehicleAttribute\022>\n"
          + "\014vehicle_type\030\t \001(\0132(.maps.fleetengine.v1.Vehicle.VehicleType\0228\n\r"
          + "license_plate\030\n"
          + " \001(\0132!.maps.fleetengine.v1.LicensePlate\0228\n"
          + "\005route\030\014"
          + " \003(\0132%.maps.fleetengine.v1.TerminalLocationB\002\030\001\022\035\n"
          + "\025current_route_segment\030\024 \001(\t\022A\n"
          + "\035current_route_segment_version\030\017"
          + " \001(\0132\032.google.protobuf.Timestamp\022J\n"
          + "\037current_route_segment_end_point\030\030"
          + " \001(\0132!.maps.fleetengine.v1.TripWaypoint\022>\n"
          + "\031remaining_distance_meters\030\022"
          + " \001(\0132\033.google.protobuf.Int32Value\0229\n"
          + "\025eta_to_first_waypoint\030\023 \001(\0132\032.google.protobuf.Timestamp\022;\n"
          + "\026remaining_time_seconds\030\031 \001(\0132\033.google.protobuf.Int32Value\0224\n"
          + "\twaypoints\030\026 \003(\0132!.maps.fleetengine.v1.TripWaypoint\0225\n"
          + "\021waypoints_version\030\020 \001(\0132\032.google.protobuf.Timestamp\022\034\n"
          + "\024back_to_back_enabled\030\027 \001(\010\022@\n"
          + "\021navigation_status\030\032 \001(\0162%.maps.fleetengine.v1.NavigationStatus\022<\n"
          + "\017device_settings\030\033"
          + " \001(\0132#.maps.fleetengine.v1.DeviceSettings\032\233\001\n"
          + "\013VehicleType\022C\n"
          + "\010category\030\001"
          + " \001(\01621.maps.fleetengine.v1.Vehicle.VehicleType.Category\"G\n"
          + "\010Category\022\013\n"
          + "\007UNKNOWN\020\000\022\010\n"
          + "\004AUTO\020\001\022\010\n"
          + "\004TAXI\020\002\022\t\n"
          + "\005TRUCK\020\003\022\017\n"
          + "\013TWO_WHEELER\020\004:P\352AM\n"
          + "\"fleetengine.googleapis.com/Vehicle\022\'providers/{provider}/vehicles/{vehicle}\"\235\001\n"
          + "\013BatteryInfo\022:\n"
          + "\016battery_status\030\001 \001(\0162\".maps.fleetengine.v1.BatteryStatus\0226\n"
          + "\014power_source\030\002 \001(\0162 .maps.fleetengine.v1.PowerSource\022\032\n"
          + "\022battery_percentage\030\003 \001(\002\"\312\001\n"
          + "\016DeviceSettings\022L\n"
          + "\030location_power_save_mode\030\001"
          + " \001(\0162*.maps.fleetengine.v1.LocationPowerSaveMode\022\032\n"
          + "\022is_power_save_mode\030\002 \001(\010\022\026\n"
          + "\016is_interactive\030\003 \001(\010\0226\n"
          + "\014battery_info\030\004 \001(\0132 .maps.fleetengine.v1.BatteryInfo\"A\n"
          + "\014LicensePlate\022\031\n"
          + "\014country_code\030\001 \001(\tB\003\340A\002\022\026\n"
          + "\016last_character\030\002 \001(\t*B\n"
          + "\014VehicleState\022\031\n"
          + "\025UNKNOWN_VEHICLE_STATE\020\000\022\013\n"
          + "\007OFFLINE\020\001\022\n\n"
          + "\006ONLINE\020\002*\222\002\n"
          + "\025LocationPowerSaveMode\022$\n"
          + " UNKNOWN_LOCATION_POWER_SAVE_MODE\020\000\022\033\n"
          + "\027LOCATION_MODE_NO_CHANGE\020\001\022.\n"
          + "*LOCATION_MODE_GPS_DISABLED_WHEN_SCREEN_OFF\020\002\022.\n"
          + "*LOCATION_MODE_ALL_DISABLED_WHEN_SCREEN_OFF\020\003\022!\n"
          + "\035LOCATION_MODE_FOREGROUND_ONLY\020\004\0223\n"
          + "/LOCATION_MODE_THROTTLE_REQUESTS_WHEN_SCREEN_OFF\020\005*\300\001\n\r"
          + "BatteryStatus\022\032\n"
          + "\026UNKNOWN_BATTERY_STATUS\020\000\022\033\n"
          + "\027BATTERY_STATUS_CHARGING\020\001\022\036\n"
          + "\032BATTERY_STATUS_DISCHARGING\020\002\022\027\n"
          + "\023BATTERY_STATUS_FULL\020\003\022\037\n"
          + "\033BATTERY_STATUS_NOT_CHARGING\020\004\022\034\n"
          + "\030BATTERY_STATUS_POWER_LOW\020\005*\211\001\n"
          + "\013PowerSource\022\030\n"
          + "\024UNKNOWN_POWER_SOURCE\020\000\022\023\n"
          + "\017POWER_SOURCE_AC\020\001\022\024\n"
          + "\020POWER_SOURCE_USB\020\002\022\031\n"
          + "\025POWER_SOURCE_WIRELESS\020\003\022\032\n"
          + "\026POWER_SOURCE_UNPLUGGED\020\004Bu\n"
          + "\032google.maps.fleetengine.v1B\010VehiclesP\001ZEgoogle.golang.org/genp"
          + "roto/googleapis/maps/fleetengine/v1;fleetengine\242\002\003CFEb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              google.maps.fleetengine.v1.FleetEngine.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.protobuf.WrappersProto.getDescriptor(),
            });
    internal_static_maps_fleetengine_v1_Vehicle_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_maps_fleetengine_v1_Vehicle_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_maps_fleetengine_v1_Vehicle_descriptor,
            new java.lang.String[] {
              "Name",
              "VehicleState",
              "SupportedTripTypes",
              "CurrentTrips",
              "LastLocation",
              "MaximumCapacity",
              "AvailableCapacity",
              "Attributes",
              "VehicleType",
              "LicensePlate",
              "Route",
              "CurrentRouteSegment",
              "CurrentRouteSegmentVersion",
              "CurrentRouteSegmentEndPoint",
              "RemainingDistanceMeters",
              "EtaToFirstWaypoint",
              "RemainingTimeSeconds",
              "Waypoints",
              "WaypointsVersion",
              "BackToBackEnabled",
              "NavigationStatus",
              "DeviceSettings",
            });
    internal_static_maps_fleetengine_v1_Vehicle_VehicleType_descriptor =
        internal_static_maps_fleetengine_v1_Vehicle_descriptor.getNestedTypes().get(0);
    internal_static_maps_fleetengine_v1_Vehicle_VehicleType_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_maps_fleetengine_v1_Vehicle_VehicleType_descriptor,
            new java.lang.String[] {
              "Category",
            });
    internal_static_maps_fleetengine_v1_BatteryInfo_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_maps_fleetengine_v1_BatteryInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_maps_fleetengine_v1_BatteryInfo_descriptor,
            new java.lang.String[] {
              "BatteryStatus", "PowerSource", "BatteryPercentage",
            });
    internal_static_maps_fleetengine_v1_DeviceSettings_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_maps_fleetengine_v1_DeviceSettings_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_maps_fleetengine_v1_DeviceSettings_descriptor,
            new java.lang.String[] {
              "LocationPowerSaveMode", "IsPowerSaveMode", "IsInteractive", "BatteryInfo",
            });
    internal_static_maps_fleetengine_v1_LicensePlate_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_maps_fleetengine_v1_LicensePlate_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_maps_fleetengine_v1_LicensePlate_descriptor,
            new java.lang.String[] {
              "CountryCode", "LastCharacter",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    google.maps.fleetengine.v1.FleetEngine.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
